/*
 * generated by Xtext 2.42.0
 */
grammar InternalAgendomat;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package agendomat.dsl.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package agendomat.dsl.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import agendomat.dsl.services.AgendomatGrammarAccess;

}
@parser::members {
	private AgendomatGrammarAccess grammarAccess;

	public void setGrammarAccess(AgendomatGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleEvent
entryRuleEvent
:
{ before(grammarAccess.getEventRule()); }
	 ruleEvent
{ after(grammarAccess.getEventRule()); } 
	 EOF 
;

// Rule Event
ruleEvent 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEventAccess().getGroup()); }
		(rule__Event__Group__0)
		{ after(grammarAccess.getEventAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleProgramItem
entryRuleProgramItem
:
{ before(grammarAccess.getProgramItemRule()); }
	 ruleProgramItem
{ after(grammarAccess.getProgramItemRule()); } 
	 EOF 
;

// Rule ProgramItem
ruleProgramItem 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getProgramItemAccess().getAlternatives()); }
		(rule__ProgramItem__Alternatives)
		{ after(grammarAccess.getProgramItemAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRulePerson
entryRulePerson
:
{ before(grammarAccess.getPersonRule()); }
	 rulePerson
{ after(grammarAccess.getPersonRule()); } 
	 EOF 
;

// Rule Person
rulePerson 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getPersonAccess().getGroup()); }
		(rule__Person__Group__0)
		{ after(grammarAccess.getPersonAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLocation
entryRuleLocation
:
{ before(grammarAccess.getLocationRule()); }
	 ruleLocation
{ after(grammarAccess.getLocationRule()); } 
	 EOF 
;

// Rule Location
ruleLocation 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLocationAccess().getGroup()); }
		(rule__Location__Group__0)
		{ after(grammarAccess.getLocationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleSession
entryRuleSession
:
{ before(grammarAccess.getSessionRule()); }
	 ruleSession
{ after(grammarAccess.getSessionRule()); } 
	 EOF 
;

// Rule Session
ruleSession 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getSessionAccess().getGroup()); }
		(rule__Session__Group__0)
		{ after(grammarAccess.getSessionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleBreak
entryRuleBreak
:
{ before(grammarAccess.getBreakRule()); }
	 ruleBreak
{ after(grammarAccess.getBreakRule()); } 
	 EOF 
;

// Rule Break
ruleBreak 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getBreakAccess().getGroup()); }
		(rule__Break__Group__0)
		{ after(grammarAccess.getBreakAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleTalk
entryRuleTalk
:
{ before(grammarAccess.getTalkRule()); }
	 ruleTalk
{ after(grammarAccess.getTalkRule()); } 
	 EOF 
;

// Rule Talk
ruleTalk 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTalkAccess().getGroup()); }
		(rule__Talk__Group__0)
		{ after(grammarAccess.getTalkAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEquipment
entryRuleEquipment
:
{ before(grammarAccess.getEquipmentRule()); }
	 ruleEquipment
{ after(grammarAccess.getEquipmentRule()); } 
	 EOF 
;

// Rule Equipment
ruleEquipment 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEquipmentAccess().getEquipmentNameAssignment()); }
		(rule__Equipment__EquipmentNameAssignment)
		{ after(grammarAccess.getEquipmentAccess().getEquipmentNameAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule Role
ruleRole
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoleAccess().getAlternatives()); }
		(rule__Role__Alternatives)
		{ after(grammarAccess.getRoleAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule LocationType
ruleLocationType
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLocationTypeAccess().getAlternatives()); }
		(rule__LocationType__Alternatives)
		{ after(grammarAccess.getLocationTypeAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Alternatives_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getGroup_2_0()); }
		(rule__Event__Group_2_0__0)
		{ after(grammarAccess.getEventAccess().getGroup_2_0()); }
	)
	|
	(
		{ before(grammarAccess.getEventAccess().getGroup_2_1()); }
		(rule__Event__Group_2_1__0)
		{ after(grammarAccess.getEventAccess().getGroup_2_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ProgramItem__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProgramItemAccess().getSessionParserRuleCall_0()); }
		ruleSession
		{ after(grammarAccess.getProgramItemAccess().getSessionParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getProgramItemAccess().getBreakParserRuleCall_1()); }
		ruleBreak
		{ after(grammarAccess.getProgramItemAccess().getBreakParserRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoleAccess().getPresenterEnumLiteralDeclaration_0()); }
		('Presenter')
		{ after(grammarAccess.getRoleAccess().getPresenterEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getRoleAccess().getTechSupportEnumLiteralDeclaration_1()); }
		('TechSupport')
		{ after(grammarAccess.getRoleAccess().getTechSupportEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getRoleAccess().getAnimatorEnumLiteralDeclaration_2()); }
		('Animator')
		{ after(grammarAccess.getRoleAccess().getAnimatorEnumLiteralDeclaration_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__LocationType__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLocationTypeAccess().getRoomEnumLiteralDeclaration_0()); }
		('Room')
		{ after(grammarAccess.getLocationTypeAccess().getRoomEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getLocationTypeAccess().getBreakAreaEnumLiteralDeclaration_1()); }
		('BreakArea')
		{ after(grammarAccess.getLocationTypeAccess().getBreakAreaEnumLiteralDeclaration_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__0__Impl
	rule__Event__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventKeyword_0()); }
	'Event'
	{ after(grammarAccess.getEventAccess().getEventKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__1__Impl
	rule__Event__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventNameAssignment_1()); }
	(rule__Event__EventNameAssignment_1)
	{ after(grammarAccess.getEventAccess().getEventNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__2__Impl
	rule__Event__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getAlternatives_2()); }
	(rule__Event__Alternatives_2)
	{ after(grammarAccess.getEventAccess().getAlternatives_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__3__Impl
	rule__Event__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_3()); }
	'{'
	{ after(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__4__Impl
	rule__Event__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getGroup_4()); }
	(rule__Event__Group_4__0)?
	{ after(grammarAccess.getEventAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__5__Impl
	rule__Event__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getPersonsAssignment_5()); }
	(rule__Event__PersonsAssignment_5)*
	{ after(grammarAccess.getEventAccess().getPersonsAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__6__Impl
	rule__Event__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLocationsAssignment_6()); }
	(rule__Event__LocationsAssignment_6)*
	{ after(grammarAccess.getEventAccess().getLocationsAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__7__Impl
	rule__Event__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getProgramItemsAssignment_7()); }
	(rule__Event__ProgramItemsAssignment_7)*
	{ after(grammarAccess.getEventAccess().getProgramItemsAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__8__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_8()); }
	'}'
	{ after(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_2_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_2_0__0__Impl
	rule__Event__Group_2_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getFromKeyword_2_0_0()); }
	'from'
	{ after(grammarAccess.getEventAccess().getFromKeyword_2_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_2_0__1__Impl
	rule__Event__Group_2_0__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventStartDateAssignment_2_0_1()); }
	(rule__Event__EventStartDateAssignment_2_0_1)
	{ after(grammarAccess.getEventAccess().getEventStartDateAssignment_2_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_0__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_2_0__2__Impl
	rule__Event__Group_2_0__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_0__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getToKeyword_2_0_2()); }
	'to'
	{ after(grammarAccess.getEventAccess().getToKeyword_2_0_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_0__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_2_0__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_0__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventEndDateAssignment_2_0_3()); }
	(rule__Event__EventEndDateAssignment_2_0_3)
	{ after(grammarAccess.getEventAccess().getEventEndDateAssignment_2_0_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_2_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_2_1__0__Impl
	rule__Event__Group_2_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getOnKeyword_2_1_0()); }
	'on'
	{ after(grammarAccess.getEventAccess().getOnKeyword_2_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_2_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_2_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventStartDateAssignment_2_1_1()); }
	(rule__Event__EventStartDateAssignment_2_1_1)
	{ after(grammarAccess.getEventAccess().getEventStartDateAssignment_2_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_4__0__Impl
	rule__Event__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getDescriptionKeyword_4_0()); }
	'Description'
	{ after(grammarAccess.getEventAccess().getDescriptionKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getDescAssignment_4_1()); }
	(rule__Event__DescAssignment_4_1)
	{ after(grammarAccess.getEventAccess().getDescAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Person__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__0__Impl
	rule__Person__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getPersonKeyword_0()); }
	'Person'
	{ after(grammarAccess.getPersonAccess().getPersonKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__1__Impl
	rule__Person__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getPersonNameAssignment_1()); }
	(rule__Person__PersonNameAssignment_1)
	{ after(grammarAccess.getPersonAccess().getPersonNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__2__Impl
	rule__Person__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRolesKeyword_2()); }
	'roles'
	{ after(grammarAccess.getPersonAccess().getRolesKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__3__Impl
	rule__Person__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getLeftSquareBracketKeyword_3()); }
	'['
	{ after(grammarAccess.getPersonAccess().getLeftSquareBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__4__Impl
	rule__Person__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRolesAssignment_4()); }
	(rule__Person__RolesAssignment_4)
	{ after(grammarAccess.getPersonAccess().getRolesAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__5__Impl
	rule__Person__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getGroup_5()); }
	(rule__Person__Group_5__0)*
	{ after(grammarAccess.getPersonAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRightSquareBracketKeyword_6()); }
	']'
	{ after(grammarAccess.getPersonAccess().getRightSquareBracketKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Person__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group_5__0__Impl
	rule__Person__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getCommaKeyword_5_0()); }
	','
	{ after(grammarAccess.getPersonAccess().getCommaKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRolesAssignment_5_1()); }
	(rule__Person__RolesAssignment_5_1)
	{ after(grammarAccess.getPersonAccess().getRolesAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Location__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__0__Impl
	rule__Location__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLocationKeyword_0()); }
	'Location'
	{ after(grammarAccess.getLocationAccess().getLocationKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__1__Impl
	rule__Location__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLocationNameAssignment_1()); }
	(rule__Location__LocationNameAssignment_1)
	{ after(grammarAccess.getLocationAccess().getLocationNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__2__Impl
	rule__Location__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getTypeKeyword_2()); }
	'type'
	{ after(grammarAccess.getLocationAccess().getTypeKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLocationTypeAssignment_3()); }
	(rule__Location__LocationTypeAssignment_3)
	{ after(grammarAccess.getLocationAccess().getLocationTypeAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__0__Impl
	rule__Session__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getSessionKeyword_0()); }
	'Session'
	{ after(grammarAccess.getSessionAccess().getSessionKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__1__Impl
	rule__Session__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getSessionNameAssignment_1()); }
	(rule__Session__SessionNameAssignment_1)
	{ after(grammarAccess.getSessionAccess().getSessionNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__2__Impl
	rule__Session__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__3__Impl
	rule__Session__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTimeKeyword_3()); }
	'Time'
	{ after(grammarAccess.getSessionAccess().getTimeKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__4__Impl
	rule__Session__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getStartTimeAssignment_4()); }
	(rule__Session__StartTimeAssignment_4)
	{ after(grammarAccess.getSessionAccess().getStartTimeAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__5__Impl
	rule__Session__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getHyphenMinusKeyword_5()); }
	'-'
	{ after(grammarAccess.getSessionAccess().getHyphenMinusKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__6__Impl
	rule__Session__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getEndTimeAssignment_6()); }
	(rule__Session__EndTimeAssignment_6)
	{ after(grammarAccess.getSessionAccess().getEndTimeAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__7__Impl
	rule__Session__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLocationKeyword_7()); }
	'Location'
	{ after(grammarAccess.getSessionAccess().getLocationKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__8__Impl
	rule__Session__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLocationAssignment_8()); }
	(rule__Session__LocationAssignment_8)
	{ after(grammarAccess.getSessionAccess().getLocationAssignment_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__9__Impl
	rule__Session__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_9()); }
	(rule__Session__Group_9__0)?
	{ after(grammarAccess.getSessionAccess().getGroup_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__10__Impl
	rule__Session__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_10()); }
	(rule__Session__Group_10__0)?
	{ after(grammarAccess.getSessionAccess().getGroup_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__11__Impl
	rule__Session__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTalksAssignment_11()); }
	(rule__Session__TalksAssignment_11)*
	{ after(grammarAccess.getSessionAccess().getTalksAssignment_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__12__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_12()); }
	'}'
	{ after(grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_9__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_9__0__Impl
	rule__Session__Group_9__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTechSupportKeyword_9_0()); }
	'TechSupport'
	{ after(grammarAccess.getSessionAccess().getTechSupportKeyword_9_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_9__1__Impl
	rule__Session__Group_9__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLeftParenthesisKeyword_9_1()); }
	'('
	{ after(grammarAccess.getSessionAccess().getLeftParenthesisKeyword_9_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_9__2__Impl
	rule__Session__Group_9__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTechSupportAssignment_9_2()); }
	(rule__Session__TechSupportAssignment_9_2)
	{ after(grammarAccess.getSessionAccess().getTechSupportAssignment_9_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_9__3__Impl
	rule__Session__Group_9__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_9_3()); }
	(rule__Session__Group_9_3__0)*
	{ after(grammarAccess.getSessionAccess().getGroup_9_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_9__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getRightParenthesisKeyword_9_4()); }
	')'
	{ after(grammarAccess.getSessionAccess().getRightParenthesisKeyword_9_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_9_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_9_3__0__Impl
	rule__Session__Group_9_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getCommaKeyword_9_3_0()); }
	','
	{ after(grammarAccess.getSessionAccess().getCommaKeyword_9_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_9_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_9_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTechSupportAssignment_9_3_1()); }
	(rule__Session__TechSupportAssignment_9_3_1)
	{ after(grammarAccess.getSessionAccess().getTechSupportAssignment_9_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_10__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10__0__Impl
	rule__Session__Group_10__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getNeedsKeyword_10_0()); }
	'Needs'
	{ after(grammarAccess.getSessionAccess().getNeedsKeyword_10_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10__1__Impl
	rule__Session__Group_10__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getEquipmentAssignment_10_1()); }
	(rule__Session__EquipmentAssignment_10_1)
	{ after(grammarAccess.getSessionAccess().getEquipmentAssignment_10_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_10_2()); }
	(rule__Session__Group_10_2__0)*
	{ after(grammarAccess.getSessionAccess().getGroup_10_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_10_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10_2__0__Impl
	rule__Session__Group_10_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getCommaKeyword_10_2_0()); }
	','
	{ after(grammarAccess.getSessionAccess().getCommaKeyword_10_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getEquipmentAssignment_10_2_1()); }
	(rule__Session__EquipmentAssignment_10_2_1)
	{ after(grammarAccess.getSessionAccess().getEquipmentAssignment_10_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Break__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__0__Impl
	rule__Break__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getBreakKeyword_0()); }
	'Break'
	{ after(grammarAccess.getBreakAccess().getBreakKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__1__Impl
	rule__Break__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getBreakNameAssignment_1()); }
	(rule__Break__BreakNameAssignment_1)
	{ after(grammarAccess.getBreakAccess().getBreakNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__2__Impl
	rule__Break__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getBreakAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__3__Impl
	rule__Break__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getTimeKeyword_3()); }
	'Time'
	{ after(grammarAccess.getBreakAccess().getTimeKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__4__Impl
	rule__Break__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getStartTimeAssignment_4()); }
	(rule__Break__StartTimeAssignment_4)
	{ after(grammarAccess.getBreakAccess().getStartTimeAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__5__Impl
	rule__Break__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getHyphenMinusKeyword_5()); }
	'-'
	{ after(grammarAccess.getBreakAccess().getHyphenMinusKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__6__Impl
	rule__Break__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getEndTimeAssignment_6()); }
	(rule__Break__EndTimeAssignment_6)
	{ after(grammarAccess.getBreakAccess().getEndTimeAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__7__Impl
	rule__Break__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getLocationKeyword_7()); }
	'Location'
	{ after(grammarAccess.getBreakAccess().getLocationKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__8__Impl
	rule__Break__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getLocationAssignment_8()); }
	(rule__Break__LocationAssignment_8)
	{ after(grammarAccess.getBreakAccess().getLocationAssignment_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__9__Impl
	rule__Break__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getGroup_9()); }
	(rule__Break__Group_9__0)?
	{ after(grammarAccess.getBreakAccess().getGroup_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__10__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getRightCurlyBracketKeyword_10()); }
	'}'
	{ after(grammarAccess.getBreakAccess().getRightCurlyBracketKeyword_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Break__Group_9__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_9__0__Impl
	rule__Break__Group_9__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getAnimatorKeyword_9_0()); }
	'Animator'
	{ after(grammarAccess.getBreakAccess().getAnimatorKeyword_9_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_9__1__Impl
	rule__Break__Group_9__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getLeftParenthesisKeyword_9_1()); }
	'('
	{ after(grammarAccess.getBreakAccess().getLeftParenthesisKeyword_9_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_9__2__Impl
	rule__Break__Group_9__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getAnimatorsAssignment_9_2()); }
	(rule__Break__AnimatorsAssignment_9_2)
	{ after(grammarAccess.getBreakAccess().getAnimatorsAssignment_9_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_9__3__Impl
	rule__Break__Group_9__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getGroup_9_3()); }
	(rule__Break__Group_9_3__0)*
	{ after(grammarAccess.getBreakAccess().getGroup_9_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_9__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getRightParenthesisKeyword_9_4()); }
	')'
	{ after(grammarAccess.getBreakAccess().getRightParenthesisKeyword_9_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Break__Group_9_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_9_3__0__Impl
	rule__Break__Group_9_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getCommaKeyword_9_3_0()); }
	','
	{ after(grammarAccess.getBreakAccess().getCommaKeyword_9_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_9_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_9_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getAnimatorsAssignment_9_3_1()); }
	(rule__Break__AnimatorsAssignment_9_3_1)
	{ after(grammarAccess.getBreakAccess().getAnimatorsAssignment_9_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Talk__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__0__Impl
	rule__Talk__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkKeyword_0()); }
	'Talk'
	{ after(grammarAccess.getTalkAccess().getTalkKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__1__Impl
	rule__Talk__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkNameAssignment_1()); }
	(rule__Talk__TalkNameAssignment_1)
	{ after(grammarAccess.getTalkAccess().getTalkNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__2__Impl
	rule__Talk__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getTalkAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__3__Impl
	rule__Talk__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTimeKeyword_3()); }
	'Time'
	{ after(grammarAccess.getTalkAccess().getTimeKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__4__Impl
	rule__Talk__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkStartTimeAssignment_4()); }
	(rule__Talk__TalkStartTimeAssignment_4)
	{ after(grammarAccess.getTalkAccess().getTalkStartTimeAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__5__Impl
	rule__Talk__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getHyphenMinusKeyword_5()); }
	'-'
	{ after(grammarAccess.getTalkAccess().getHyphenMinusKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__6__Impl
	rule__Talk__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkEndTimeAssignment_6()); }
	(rule__Talk__TalkEndTimeAssignment_6)
	{ after(grammarAccess.getTalkAccess().getTalkEndTimeAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__7__Impl
	rule__Talk__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getPresenterKeyword_7()); }
	'Presenter'
	{ after(grammarAccess.getTalkAccess().getPresenterKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__8__Impl
	rule__Talk__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getLeftParenthesisKeyword_8()); }
	'('
	{ after(grammarAccess.getTalkAccess().getLeftParenthesisKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__9__Impl
	rule__Talk__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getPresentersAssignment_9()); }
	(rule__Talk__PresentersAssignment_9)
	{ after(grammarAccess.getTalkAccess().getPresentersAssignment_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__10__Impl
	rule__Talk__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getGroup_10()); }
	(rule__Talk__Group_10__0)*
	{ after(grammarAccess.getTalkAccess().getGroup_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__11__Impl
	rule__Talk__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getRightParenthesisKeyword_11()); }
	')'
	{ after(grammarAccess.getTalkAccess().getRightParenthesisKeyword_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__12__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getRightCurlyBracketKeyword_12()); }
	'}'
	{ after(grammarAccess.getTalkAccess().getRightCurlyBracketKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Talk__Group_10__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group_10__0__Impl
	rule__Talk__Group_10__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group_10__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getCommaKeyword_10_0()); }
	','
	{ after(grammarAccess.getTalkAccess().getCommaKeyword_10_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group_10__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group_10__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group_10__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getPresentersAssignment_10_1()); }
	(rule__Talk__PresentersAssignment_10_1)
	{ after(grammarAccess.getTalkAccess().getPresentersAssignment_10_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__EventNameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getEventNameSTRINGTerminalRuleCall_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getEventAccess().getEventNameSTRINGTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__EventStartDateAssignment_2_0_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getEventStartDateSTRINGTerminalRuleCall_2_0_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getEventAccess().getEventStartDateSTRINGTerminalRuleCall_2_0_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__EventEndDateAssignment_2_0_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getEventEndDateSTRINGTerminalRuleCall_2_0_3_0()); }
		RULE_STRING
		{ after(grammarAccess.getEventAccess().getEventEndDateSTRINGTerminalRuleCall_2_0_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__EventStartDateAssignment_2_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getEventStartDateSTRINGTerminalRuleCall_2_1_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getEventAccess().getEventStartDateSTRINGTerminalRuleCall_2_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__DescAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getDescSTRINGTerminalRuleCall_4_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getEventAccess().getDescSTRINGTerminalRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__PersonsAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_5_0()); }
		rulePerson
		{ after(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__LocationsAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_6_0()); }
		ruleLocation
		{ after(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__ProgramItemsAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_7_0()); }
		ruleProgramItem
		{ after(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__PersonNameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPersonAccess().getPersonNameSTRINGTerminalRuleCall_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getPersonAccess().getPersonNameSTRINGTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__RolesAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_4_0()); }
		ruleRole
		{ after(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__RolesAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_5_1_0()); }
		ruleRole
		{ after(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__LocationNameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLocationAccess().getLocationNameSTRINGTerminalRuleCall_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getLocationAccess().getLocationNameSTRINGTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__LocationTypeAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLocationAccess().getLocationTypeLocationTypeEnumRuleCall_3_0()); }
		ruleLocationType
		{ after(grammarAccess.getLocationAccess().getLocationTypeLocationTypeEnumRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__SessionNameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getSessionNameSTRINGTerminalRuleCall_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getSessionAccess().getSessionNameSTRINGTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__StartTimeAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getStartTimeSTRINGTerminalRuleCall_4_0()); }
		RULE_STRING
		{ after(grammarAccess.getSessionAccess().getStartTimeSTRINGTerminalRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__EndTimeAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getEndTimeSTRINGTerminalRuleCall_6_0()); }
		RULE_STRING
		{ after(grammarAccess.getSessionAccess().getEndTimeSTRINGTerminalRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__LocationAssignment_8
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getLocationLocationCrossReference_8_0()); }
		(
			{ before(grammarAccess.getSessionAccess().getLocationLocationSTRINGTerminalRuleCall_8_0_1()); }
			RULE_STRING
			{ after(grammarAccess.getSessionAccess().getLocationLocationSTRINGTerminalRuleCall_8_0_1()); }
		)
		{ after(grammarAccess.getSessionAccess().getLocationLocationCrossReference_8_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__TechSupportAssignment_9_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_9_2_0()); }
		(
			{ before(grammarAccess.getSessionAccess().getTechSupportPersonSTRINGTerminalRuleCall_9_2_0_1()); }
			RULE_STRING
			{ after(grammarAccess.getSessionAccess().getTechSupportPersonSTRINGTerminalRuleCall_9_2_0_1()); }
		)
		{ after(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_9_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__TechSupportAssignment_9_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_9_3_1_0()); }
		(
			{ before(grammarAccess.getSessionAccess().getTechSupportPersonSTRINGTerminalRuleCall_9_3_1_0_1()); }
			RULE_STRING
			{ after(grammarAccess.getSessionAccess().getTechSupportPersonSTRINGTerminalRuleCall_9_3_1_0_1()); }
		)
		{ after(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_9_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__EquipmentAssignment_10_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_10_1_0()); }
		ruleEquipment
		{ after(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_10_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__EquipmentAssignment_10_2_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_10_2_1_0()); }
		ruleEquipment
		{ after(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_10_2_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__TalksAssignment_11
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_0()); }
		ruleTalk
		{ after(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__BreakNameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getBreakNameSTRINGTerminalRuleCall_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getBreakAccess().getBreakNameSTRINGTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__StartTimeAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getStartTimeSTRINGTerminalRuleCall_4_0()); }
		RULE_STRING
		{ after(grammarAccess.getBreakAccess().getStartTimeSTRINGTerminalRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__EndTimeAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getEndTimeSTRINGTerminalRuleCall_6_0()); }
		RULE_STRING
		{ after(grammarAccess.getBreakAccess().getEndTimeSTRINGTerminalRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__LocationAssignment_8
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getLocationLocationCrossReference_8_0()); }
		(
			{ before(grammarAccess.getBreakAccess().getLocationLocationSTRINGTerminalRuleCall_8_0_1()); }
			RULE_STRING
			{ after(grammarAccess.getBreakAccess().getLocationLocationSTRINGTerminalRuleCall_8_0_1()); }
		)
		{ after(grammarAccess.getBreakAccess().getLocationLocationCrossReference_8_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__AnimatorsAssignment_9_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_9_2_0()); }
		(
			{ before(grammarAccess.getBreakAccess().getAnimatorsPersonSTRINGTerminalRuleCall_9_2_0_1()); }
			RULE_STRING
			{ after(grammarAccess.getBreakAccess().getAnimatorsPersonSTRINGTerminalRuleCall_9_2_0_1()); }
		)
		{ after(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_9_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__AnimatorsAssignment_9_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_9_3_1_0()); }
		(
			{ before(grammarAccess.getBreakAccess().getAnimatorsPersonSTRINGTerminalRuleCall_9_3_1_0_1()); }
			RULE_STRING
			{ after(grammarAccess.getBreakAccess().getAnimatorsPersonSTRINGTerminalRuleCall_9_3_1_0_1()); }
		)
		{ after(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_9_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__TalkNameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getTalkNameSTRINGTerminalRuleCall_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getTalkAccess().getTalkNameSTRINGTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__TalkStartTimeAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getTalkStartTimeSTRINGTerminalRuleCall_4_0()); }
		RULE_STRING
		{ after(grammarAccess.getTalkAccess().getTalkStartTimeSTRINGTerminalRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__TalkEndTimeAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getTalkEndTimeSTRINGTerminalRuleCall_6_0()); }
		RULE_STRING
		{ after(grammarAccess.getTalkAccess().getTalkEndTimeSTRINGTerminalRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__PresentersAssignment_9
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_9_0()); }
		(
			{ before(grammarAccess.getTalkAccess().getPresentersPersonSTRINGTerminalRuleCall_9_0_1()); }
			RULE_STRING
			{ after(grammarAccess.getTalkAccess().getPresentersPersonSTRINGTerminalRuleCall_9_0_1()); }
		)
		{ after(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_9_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__PresentersAssignment_10_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_10_1_0()); }
		(
			{ before(grammarAccess.getTalkAccess().getPresentersPersonSTRINGTerminalRuleCall_10_1_0_1()); }
			RULE_STRING
			{ after(grammarAccess.getTalkAccess().getPresentersPersonSTRINGTerminalRuleCall_10_1_0_1()); }
		)
		{ after(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_10_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__EquipmentNameAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEquipmentAccess().getEquipmentNameSTRINGTerminalRuleCall_0()); }
		RULE_STRING
		{ after(grammarAccess.getEquipmentAccess().getEquipmentNameSTRINGTerminalRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
