/*
 * generated by Xtext 2.42.0
 */
grammar InternalAgendomat;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package agendomat.dsl.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package agendomat.dsl.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import agendomat.dsl.services.AgendomatGrammarAccess;

}
@parser::members {
	private AgendomatGrammarAccess grammarAccess;

	public void setGrammarAccess(AgendomatGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleModel
entryRuleModel
:
{ before(grammarAccess.getModelRule()); }
	 ruleModel
{ after(grammarAccess.getModelRule()); } 
	 EOF 
;

// Rule Model
ruleModel 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getModelAccess().getGroup()); }
		(rule__Model__Group__0)
		{ after(grammarAccess.getModelAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleProgramItem
entryRuleProgramItem
:
{ before(grammarAccess.getProgramItemRule()); }
	 ruleProgramItem
{ after(grammarAccess.getProgramItemRule()); } 
	 EOF 
;

// Rule ProgramItem
ruleProgramItem 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getProgramItemAccess().getAlternatives()); }
		(rule__ProgramItem__Alternatives)
		{ after(grammarAccess.getProgramItemAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEvent
entryRuleEvent
:
{ before(grammarAccess.getEventRule()); }
	 ruleEvent
{ after(grammarAccess.getEventRule()); } 
	 EOF 
;

// Rule Event
ruleEvent 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEventAccess().getGroup()); }
		(rule__Event__Group__0)
		{ after(grammarAccess.getEventAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEString
entryRuleEString
:
{ before(grammarAccess.getEStringRule()); }
	 ruleEString
{ after(grammarAccess.getEStringRule()); } 
	 EOF 
;

// Rule EString
ruleEString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEStringAccess().getAlternatives()); }
		(rule__EString__Alternatives)
		{ after(grammarAccess.getEStringAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRulePerson
entryRulePerson
:
{ before(grammarAccess.getPersonRule()); }
	 rulePerson
{ after(grammarAccess.getPersonRule()); } 
	 EOF 
;

// Rule Person
rulePerson 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getPersonAccess().getGroup()); }
		(rule__Person__Group__0)
		{ after(grammarAccess.getPersonAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLocation
entryRuleLocation
:
{ before(grammarAccess.getLocationRule()); }
	 ruleLocation
{ after(grammarAccess.getLocationRule()); } 
	 EOF 
;

// Rule Location
ruleLocation 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLocationAccess().getGroup()); }
		(rule__Location__Group__0)
		{ after(grammarAccess.getLocationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleSession
entryRuleSession
:
{ before(grammarAccess.getSessionRule()); }
	 ruleSession
{ after(grammarAccess.getSessionRule()); } 
	 EOF 
;

// Rule Session
ruleSession 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getSessionAccess().getGroup()); }
		(rule__Session__Group__0)
		{ after(grammarAccess.getSessionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleBreak
entryRuleBreak
:
{ before(grammarAccess.getBreakRule()); }
	 ruleBreak
{ after(grammarAccess.getBreakRule()); } 
	 EOF 
;

// Rule Break
ruleBreak 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getBreakAccess().getGroup()); }
		(rule__Break__Group__0)
		{ after(grammarAccess.getBreakAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleTalk
entryRuleTalk
:
{ before(grammarAccess.getTalkRule()); }
	 ruleTalk
{ after(grammarAccess.getTalkRule()); } 
	 EOF 
;

// Rule Talk
ruleTalk 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTalkAccess().getGroup()); }
		(rule__Talk__Group__0)
		{ after(grammarAccess.getTalkAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEquipment
entryRuleEquipment
:
{ before(grammarAccess.getEquipmentRule()); }
	 ruleEquipment
{ after(grammarAccess.getEquipmentRule()); } 
	 EOF 
;

// Rule Equipment
ruleEquipment 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEquipmentAccess().getGroup()); }
		(rule__Equipment__Group__0)
		{ after(grammarAccess.getEquipmentAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule Role
ruleRole
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoleAccess().getAlternatives()); }
		(rule__Role__Alternatives)
		{ after(grammarAccess.getRoleAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule LocationType
ruleLocationType
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLocationTypeAccess().getAlternatives()); }
		(rule__LocationType__Alternatives)
		{ after(grammarAccess.getLocationTypeAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ProgramItem__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProgramItemAccess().getSessionParserRuleCall_0()); }
		ruleSession
		{ after(grammarAccess.getProgramItemAccess().getSessionParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getProgramItemAccess().getBreakParserRuleCall_1()); }
		ruleBreak
		{ after(grammarAccess.getProgramItemAccess().getBreakParserRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EString__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
		RULE_STRING
		{ after(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
		RULE_ID
		{ after(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Role__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoleAccess().getPresenterEnumLiteralDeclaration_0()); }
		('Presenter')
		{ after(grammarAccess.getRoleAccess().getPresenterEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getRoleAccess().getTechSupportEnumLiteralDeclaration_1()); }
		('TechSupport')
		{ after(grammarAccess.getRoleAccess().getTechSupportEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getRoleAccess().getAnimatorEnumLiteralDeclaration_2()); }
		('Animator')
		{ after(grammarAccess.getRoleAccess().getAnimatorEnumLiteralDeclaration_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__LocationType__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLocationTypeAccess().getRoomEnumLiteralDeclaration_0()); }
		('Room')
		{ after(grammarAccess.getLocationTypeAccess().getRoomEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getLocationTypeAccess().getBreakAreaEnumLiteralDeclaration_1()); }
		('BreakArea')
		{ after(grammarAccess.getLocationTypeAccess().getBreakAreaEnumLiteralDeclaration_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__0__Impl
	rule__Model__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getModelAction_0()); }
	()
	{ after(grammarAccess.getModelAccess().getModelAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__1__Impl
	rule__Model__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getModelKeyword_1()); }
	'Model'
	{ after(grammarAccess.getModelAccess().getModelKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__2__Impl
	rule__Model__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__3__Impl
	rule__Model__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getGroup_3()); }
	(rule__Model__Group_3__0)?
	{ after(grammarAccess.getModelAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getRightCurlyBracketKeyword_4()); }
	'}'
	{ after(grammarAccess.getModelAccess().getRightCurlyBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Model__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group_3__0__Impl
	rule__Model__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getEventsKeyword_3_0()); }
	'events'
	{ after(grammarAccess.getModelAccess().getEventsKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group_3__1__Impl
	rule__Model__Group_3__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_3_1()); }
	'{'
	{ after(grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group_3__2__Impl
	rule__Model__Group_3__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getEventsAssignment_3_2()); }
	(rule__Model__EventsAssignment_3_2)
	{ after(grammarAccess.getModelAccess().getEventsAssignment_3_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group_3__3__Impl
	rule__Model__Group_3__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getGroup_3_3()); }
	(rule__Model__Group_3_3__0)*
	{ after(grammarAccess.getModelAccess().getGroup_3_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group_3__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getRightCurlyBracketKeyword_3_4()); }
	'}'
	{ after(grammarAccess.getModelAccess().getRightCurlyBracketKeyword_3_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Model__Group_3_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group_3_3__0__Impl
	rule__Model__Group_3_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getCommaKeyword_3_3_0()); }
	','
	{ after(grammarAccess.getModelAccess().getCommaKeyword_3_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Model__Group_3_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__Group_3_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getModelAccess().getEventsAssignment_3_3_1()); }
	(rule__Model__EventsAssignment_3_3_1)
	{ after(grammarAccess.getModelAccess().getEventsAssignment_3_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__0__Impl
	rule__Event__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventKeyword_0()); }
	'Event'
	{ after(grammarAccess.getEventAccess().getEventKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__1__Impl
	rule__Event__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__2__Impl
	rule__Event__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventNameKeyword_2()); }
	'eventName'
	{ after(grammarAccess.getEventAccess().getEventNameKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__3__Impl
	rule__Event__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventNameAssignment_3()); }
	(rule__Event__EventNameAssignment_3)
	{ after(grammarAccess.getEventAccess().getEventNameAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__4__Impl
	rule__Event__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventStartDateKeyword_4()); }
	'eventStartDate'
	{ after(grammarAccess.getEventAccess().getEventStartDateKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__5__Impl
	rule__Event__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventStartDateAssignment_5()); }
	(rule__Event__EventStartDateAssignment_5)
	{ after(grammarAccess.getEventAccess().getEventStartDateAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__6__Impl
	rule__Event__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventEndDateKeyword_6()); }
	'eventEndDate'
	{ after(grammarAccess.getEventAccess().getEventEndDateKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__7__Impl
	rule__Event__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getEventEndDateAssignment_7()); }
	(rule__Event__EventEndDateAssignment_7)
	{ after(grammarAccess.getEventAccess().getEventEndDateAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__8__Impl
	rule__Event__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getGroup_8()); }
	(rule__Event__Group_8__0)?
	{ after(grammarAccess.getEventAccess().getGroup_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__9__Impl
	rule__Event__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getGroup_9()); }
	(rule__Event__Group_9__0)?
	{ after(grammarAccess.getEventAccess().getGroup_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__10__Impl
	rule__Event__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getGroup_10()); }
	(rule__Event__Group_10__0)?
	{ after(grammarAccess.getEventAccess().getGroup_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__11__Impl
	rule__Event__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getGroup_11()); }
	(rule__Event__Group_11__0)?
	{ after(grammarAccess.getEventAccess().getGroup_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group__12__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_12()); }
	'}'
	{ after(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_8__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_8__0__Impl
	rule__Event__Group_8__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_8__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getDescKeyword_8_0()); }
	'desc'
	{ after(grammarAccess.getEventAccess().getDescKeyword_8_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_8__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_8__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_8__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getDescAssignment_8_1()); }
	(rule__Event__DescAssignment_8_1)
	{ after(grammarAccess.getEventAccess().getDescAssignment_8_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_9__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_9__0__Impl
	rule__Event__Group_9__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getPersonsKeyword_9_0()); }
	'persons'
	{ after(grammarAccess.getEventAccess().getPersonsKeyword_9_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_9__1__Impl
	rule__Event__Group_9__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_9_1()); }
	'{'
	{ after(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_9_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_9__2__Impl
	rule__Event__Group_9__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getPersonsAssignment_9_2()); }
	(rule__Event__PersonsAssignment_9_2)
	{ after(grammarAccess.getEventAccess().getPersonsAssignment_9_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_9__3__Impl
	rule__Event__Group_9__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getGroup_9_3()); }
	(rule__Event__Group_9_3__0)*
	{ after(grammarAccess.getEventAccess().getGroup_9_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_9__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_9_4()); }
	'}'
	{ after(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_9_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_9_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_9_3__0__Impl
	rule__Event__Group_9_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getCommaKeyword_9_3_0()); }
	','
	{ after(grammarAccess.getEventAccess().getCommaKeyword_9_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_9_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_9_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getPersonsAssignment_9_3_1()); }
	(rule__Event__PersonsAssignment_9_3_1)
	{ after(grammarAccess.getEventAccess().getPersonsAssignment_9_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_10__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_10__0__Impl
	rule__Event__Group_10__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getProgramItemsKeyword_10_0()); }
	'programItems'
	{ after(grammarAccess.getEventAccess().getProgramItemsKeyword_10_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_10__1__Impl
	rule__Event__Group_10__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_10_1()); }
	'{'
	{ after(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_10_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_10__2__Impl
	rule__Event__Group_10__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getProgramItemsAssignment_10_2()); }
	(rule__Event__ProgramItemsAssignment_10_2)
	{ after(grammarAccess.getEventAccess().getProgramItemsAssignment_10_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_10__3__Impl
	rule__Event__Group_10__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getGroup_10_3()); }
	(rule__Event__Group_10_3__0)*
	{ after(grammarAccess.getEventAccess().getGroup_10_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_10__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_10_4()); }
	'}'
	{ after(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_10_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_10_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_10_3__0__Impl
	rule__Event__Group_10_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getCommaKeyword_10_3_0()); }
	','
	{ after(grammarAccess.getEventAccess().getCommaKeyword_10_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_10_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_10_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getProgramItemsAssignment_10_3_1()); }
	(rule__Event__ProgramItemsAssignment_10_3_1)
	{ after(grammarAccess.getEventAccess().getProgramItemsAssignment_10_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_11__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_11__0__Impl
	rule__Event__Group_11__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLocationsKeyword_11_0()); }
	'locations'
	{ after(grammarAccess.getEventAccess().getLocationsKeyword_11_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_11__1__Impl
	rule__Event__Group_11__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_11_1()); }
	'{'
	{ after(grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_11_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_11__2__Impl
	rule__Event__Group_11__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLocationsAssignment_11_2()); }
	(rule__Event__LocationsAssignment_11_2)
	{ after(grammarAccess.getEventAccess().getLocationsAssignment_11_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_11__3__Impl
	rule__Event__Group_11__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getGroup_11_3()); }
	(rule__Event__Group_11_3__0)*
	{ after(grammarAccess.getEventAccess().getGroup_11_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_11__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_11_4()); }
	'}'
	{ after(grammarAccess.getEventAccess().getRightCurlyBracketKeyword_11_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Event__Group_11_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_11_3__0__Impl
	rule__Event__Group_11_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getCommaKeyword_11_3_0()); }
	','
	{ after(grammarAccess.getEventAccess().getCommaKeyword_11_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Event__Group_11_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Group_11_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventAccess().getLocationsAssignment_11_3_1()); }
	(rule__Event__LocationsAssignment_11_3_1)
	{ after(grammarAccess.getEventAccess().getLocationsAssignment_11_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Person__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__0__Impl
	rule__Person__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getPersonKeyword_0()); }
	'Person'
	{ after(grammarAccess.getPersonAccess().getPersonKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__1__Impl
	rule__Person__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getPersonAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__2__Impl
	rule__Person__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getPersonNameKeyword_2()); }
	'personName'
	{ after(grammarAccess.getPersonAccess().getPersonNameKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__3__Impl
	rule__Person__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getPersonNameAssignment_3()); }
	(rule__Person__PersonNameAssignment_3)
	{ after(grammarAccess.getPersonAccess().getPersonNameAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__4__Impl
	rule__Person__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRolesKeyword_4()); }
	'roles'
	{ after(grammarAccess.getPersonAccess().getRolesKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__5__Impl
	rule__Person__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getLeftCurlyBracketKeyword_5()); }
	'{'
	{ after(grammarAccess.getPersonAccess().getLeftCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__6__Impl
	rule__Person__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRolesAssignment_6()); }
	(rule__Person__RolesAssignment_6)
	{ after(grammarAccess.getPersonAccess().getRolesAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__7__Impl
	rule__Person__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getGroup_7()); }
	(rule__Person__Group_7__0)*
	{ after(grammarAccess.getPersonAccess().getGroup_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__8__Impl
	rule__Person__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRightCurlyBracketKeyword_8()); }
	'}'
	{ after(grammarAccess.getPersonAccess().getRightCurlyBracketKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group__9__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRightCurlyBracketKeyword_9()); }
	'}'
	{ after(grammarAccess.getPersonAccess().getRightCurlyBracketKeyword_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Person__Group_7__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group_7__0__Impl
	rule__Person__Group_7__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group_7__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getCommaKeyword_7_0()); }
	','
	{ after(grammarAccess.getPersonAccess().getCommaKeyword_7_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group_7__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Person__Group_7__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__Group_7__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPersonAccess().getRolesAssignment_7_1()); }
	(rule__Person__RolesAssignment_7_1)
	{ after(grammarAccess.getPersonAccess().getRolesAssignment_7_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Location__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__0__Impl
	rule__Location__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLocationKeyword_0()); }
	'Location'
	{ after(grammarAccess.getLocationAccess().getLocationKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__1__Impl
	rule__Location__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getLocationAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__2__Impl
	rule__Location__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLocationNameKeyword_2()); }
	'locationName'
	{ after(grammarAccess.getLocationAccess().getLocationNameKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__3__Impl
	rule__Location__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLocationNameAssignment_3()); }
	(rule__Location__LocationNameAssignment_3)
	{ after(grammarAccess.getLocationAccess().getLocationNameAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__4__Impl
	rule__Location__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLocationTypeKeyword_4()); }
	'locationType'
	{ after(grammarAccess.getLocationAccess().getLocationTypeKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__5__Impl
	rule__Location__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getLocationTypeAssignment_5()); }
	(rule__Location__LocationTypeAssignment_5)
	{ after(grammarAccess.getLocationAccess().getLocationTypeAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Location__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLocationAccess().getRightCurlyBracketKeyword_6()); }
	'}'
	{ after(grammarAccess.getLocationAccess().getRightCurlyBracketKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__0__Impl
	rule__Session__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getSessionKeyword_0()); }
	'Session'
	{ after(grammarAccess.getSessionAccess().getSessionKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__1__Impl
	rule__Session__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__2__Impl
	rule__Session__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getSessionNameKeyword_2()); }
	'sessionName'
	{ after(grammarAccess.getSessionAccess().getSessionNameKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__3__Impl
	rule__Session__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getSessionNameAssignment_3()); }
	(rule__Session__SessionNameAssignment_3)
	{ after(grammarAccess.getSessionAccess().getSessionNameAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__4__Impl
	rule__Session__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getStartTimeKeyword_4()); }
	'startTime'
	{ after(grammarAccess.getSessionAccess().getStartTimeKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__5__Impl
	rule__Session__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getStartTimeAssignment_5()); }
	(rule__Session__StartTimeAssignment_5)
	{ after(grammarAccess.getSessionAccess().getStartTimeAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__6__Impl
	rule__Session__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getEndTimeKeyword_6()); }
	'endTime'
	{ after(grammarAccess.getSessionAccess().getEndTimeKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__7__Impl
	rule__Session__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getEndTimeAssignment_7()); }
	(rule__Session__EndTimeAssignment_7)
	{ after(grammarAccess.getSessionAccess().getEndTimeAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__8__Impl
	rule__Session__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLocationKeyword_8()); }
	'location'
	{ after(grammarAccess.getSessionAccess().getLocationKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__9__Impl
	rule__Session__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLocationAssignment_9()); }
	(rule__Session__LocationAssignment_9)
	{ after(grammarAccess.getSessionAccess().getLocationAssignment_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__10__Impl
	rule__Session__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_10()); }
	(rule__Session__Group_10__0)?
	{ after(grammarAccess.getSessionAccess().getGroup_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__11__Impl
	rule__Session__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_11()); }
	(rule__Session__Group_11__0)?
	{ after(grammarAccess.getSessionAccess().getGroup_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__12__Impl
	rule__Session__Group__13
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_12()); }
	(rule__Session__Group_12__0)?
	{ after(grammarAccess.getSessionAccess().getGroup_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__13
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group__13__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group__13__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_13()); }
	'}'
	{ after(grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_13()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_10__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10__0__Impl
	rule__Session__Group_10__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTechSupportKeyword_10_0()); }
	'techSupport'
	{ after(grammarAccess.getSessionAccess().getTechSupportKeyword_10_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10__1__Impl
	rule__Session__Group_10__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLeftParenthesisKeyword_10_1()); }
	'('
	{ after(grammarAccess.getSessionAccess().getLeftParenthesisKeyword_10_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10__2__Impl
	rule__Session__Group_10__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTechSupportAssignment_10_2()); }
	(rule__Session__TechSupportAssignment_10_2)
	{ after(grammarAccess.getSessionAccess().getTechSupportAssignment_10_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10__3__Impl
	rule__Session__Group_10__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_10_3()); }
	(rule__Session__Group_10_3__0)*
	{ after(grammarAccess.getSessionAccess().getGroup_10_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getRightParenthesisKeyword_10_4()); }
	')'
	{ after(grammarAccess.getSessionAccess().getRightParenthesisKeyword_10_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_10_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10_3__0__Impl
	rule__Session__Group_10_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getCommaKeyword_10_3_0()); }
	','
	{ after(grammarAccess.getSessionAccess().getCommaKeyword_10_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_10_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_10_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTechSupportAssignment_10_3_1()); }
	(rule__Session__TechSupportAssignment_10_3_1)
	{ after(grammarAccess.getSessionAccess().getTechSupportAssignment_10_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_11__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_11__0__Impl
	rule__Session__Group_11__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTalksKeyword_11_0()); }
	'talks'
	{ after(grammarAccess.getSessionAccess().getTalksKeyword_11_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_11__1__Impl
	rule__Session__Group_11__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_11_1()); }
	'{'
	{ after(grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_11_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_11__2__Impl
	rule__Session__Group_11__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTalksAssignment_11_2()); }
	(rule__Session__TalksAssignment_11_2)
	{ after(grammarAccess.getSessionAccess().getTalksAssignment_11_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_11__3__Impl
	rule__Session__Group_11__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_11_3()); }
	(rule__Session__Group_11_3__0)*
	{ after(grammarAccess.getSessionAccess().getGroup_11_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_11__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_11_4()); }
	'}'
	{ after(grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_11_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_11_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_11_3__0__Impl
	rule__Session__Group_11_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getCommaKeyword_11_3_0()); }
	','
	{ after(grammarAccess.getSessionAccess().getCommaKeyword_11_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_11_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_11_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getTalksAssignment_11_3_1()); }
	(rule__Session__TalksAssignment_11_3_1)
	{ after(grammarAccess.getSessionAccess().getTalksAssignment_11_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_12__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_12__0__Impl
	rule__Session__Group_12__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getEquipmentKeyword_12_0()); }
	'equipment'
	{ after(grammarAccess.getSessionAccess().getEquipmentKeyword_12_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_12__1__Impl
	rule__Session__Group_12__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_12_1()); }
	'{'
	{ after(grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_12_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_12__2__Impl
	rule__Session__Group_12__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getEquipmentAssignment_12_2()); }
	(rule__Session__EquipmentAssignment_12_2)
	{ after(grammarAccess.getSessionAccess().getEquipmentAssignment_12_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_12__3__Impl
	rule__Session__Group_12__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getGroup_12_3()); }
	(rule__Session__Group_12_3__0)*
	{ after(grammarAccess.getSessionAccess().getGroup_12_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_12__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_12_4()); }
	'}'
	{ after(grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_12_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Session__Group_12_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_12_3__0__Impl
	rule__Session__Group_12_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getCommaKeyword_12_3_0()); }
	','
	{ after(grammarAccess.getSessionAccess().getCommaKeyword_12_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Session__Group_12_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__Group_12_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSessionAccess().getEquipmentAssignment_12_3_1()); }
	(rule__Session__EquipmentAssignment_12_3_1)
	{ after(grammarAccess.getSessionAccess().getEquipmentAssignment_12_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Break__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__0__Impl
	rule__Break__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getBreakKeyword_0()); }
	'Break'
	{ after(grammarAccess.getBreakAccess().getBreakKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__1__Impl
	rule__Break__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getBreakAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__2__Impl
	rule__Break__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getBreakNameKeyword_2()); }
	'breakName'
	{ after(grammarAccess.getBreakAccess().getBreakNameKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__3__Impl
	rule__Break__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getBreakNameAssignment_3()); }
	(rule__Break__BreakNameAssignment_3)
	{ after(grammarAccess.getBreakAccess().getBreakNameAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__4__Impl
	rule__Break__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getStartTimeKeyword_4()); }
	'startTime'
	{ after(grammarAccess.getBreakAccess().getStartTimeKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__5__Impl
	rule__Break__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getStartTimeAssignment_5()); }
	(rule__Break__StartTimeAssignment_5)
	{ after(grammarAccess.getBreakAccess().getStartTimeAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__6__Impl
	rule__Break__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getEndTimeKeyword_6()); }
	'endTime'
	{ after(grammarAccess.getBreakAccess().getEndTimeKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__7__Impl
	rule__Break__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getEndTimeAssignment_7()); }
	(rule__Break__EndTimeAssignment_7)
	{ after(grammarAccess.getBreakAccess().getEndTimeAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__8__Impl
	rule__Break__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getLocationKeyword_8()); }
	'location'
	{ after(grammarAccess.getBreakAccess().getLocationKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__9__Impl
	rule__Break__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getLocationAssignment_9()); }
	(rule__Break__LocationAssignment_9)
	{ after(grammarAccess.getBreakAccess().getLocationAssignment_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__10__Impl
	rule__Break__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getGroup_10()); }
	(rule__Break__Group_10__0)?
	{ after(grammarAccess.getBreakAccess().getGroup_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group__11__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getRightCurlyBracketKeyword_11()); }
	'}'
	{ after(grammarAccess.getBreakAccess().getRightCurlyBracketKeyword_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Break__Group_10__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_10__0__Impl
	rule__Break__Group_10__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getAnimatorsKeyword_10_0()); }
	'animators'
	{ after(grammarAccess.getBreakAccess().getAnimatorsKeyword_10_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_10__1__Impl
	rule__Break__Group_10__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getLeftParenthesisKeyword_10_1()); }
	'('
	{ after(grammarAccess.getBreakAccess().getLeftParenthesisKeyword_10_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_10__2__Impl
	rule__Break__Group_10__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getAnimatorsAssignment_10_2()); }
	(rule__Break__AnimatorsAssignment_10_2)
	{ after(grammarAccess.getBreakAccess().getAnimatorsAssignment_10_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_10__3__Impl
	rule__Break__Group_10__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getGroup_10_3()); }
	(rule__Break__Group_10_3__0)*
	{ after(grammarAccess.getBreakAccess().getGroup_10_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_10__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getRightParenthesisKeyword_10_4()); }
	')'
	{ after(grammarAccess.getBreakAccess().getRightParenthesisKeyword_10_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Break__Group_10_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_10_3__0__Impl
	rule__Break__Group_10_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getCommaKeyword_10_3_0()); }
	','
	{ after(grammarAccess.getBreakAccess().getCommaKeyword_10_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Break__Group_10_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__Group_10_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBreakAccess().getAnimatorsAssignment_10_3_1()); }
	(rule__Break__AnimatorsAssignment_10_3_1)
	{ after(grammarAccess.getBreakAccess().getAnimatorsAssignment_10_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Talk__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__0__Impl
	rule__Talk__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkKeyword_0()); }
	'Talk'
	{ after(grammarAccess.getTalkAccess().getTalkKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__1__Impl
	rule__Talk__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getTalkAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__2__Impl
	rule__Talk__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkNameKeyword_2()); }
	'talkName'
	{ after(grammarAccess.getTalkAccess().getTalkNameKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__3__Impl
	rule__Talk__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkNameAssignment_3()); }
	(rule__Talk__TalkNameAssignment_3)
	{ after(grammarAccess.getTalkAccess().getTalkNameAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__4__Impl
	rule__Talk__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkStartTimeKeyword_4()); }
	'talkStartTime'
	{ after(grammarAccess.getTalkAccess().getTalkStartTimeKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__5__Impl
	rule__Talk__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkStartTimeAssignment_5()); }
	(rule__Talk__TalkStartTimeAssignment_5)
	{ after(grammarAccess.getTalkAccess().getTalkStartTimeAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__6__Impl
	rule__Talk__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkEndTimeKeyword_6()); }
	'talkEndTime'
	{ after(grammarAccess.getTalkAccess().getTalkEndTimeKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__7__Impl
	rule__Talk__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getTalkEndTimeAssignment_7()); }
	(rule__Talk__TalkEndTimeAssignment_7)
	{ after(grammarAccess.getTalkAccess().getTalkEndTimeAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__8__Impl
	rule__Talk__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getPresentersKeyword_8()); }
	'presenters'
	{ after(grammarAccess.getTalkAccess().getPresentersKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__9__Impl
	rule__Talk__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getLeftParenthesisKeyword_9()); }
	'('
	{ after(grammarAccess.getTalkAccess().getLeftParenthesisKeyword_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__10__Impl
	rule__Talk__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getPresentersAssignment_10()); }
	(rule__Talk__PresentersAssignment_10)
	{ after(grammarAccess.getTalkAccess().getPresentersAssignment_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__11__Impl
	rule__Talk__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getGroup_11()); }
	(rule__Talk__Group_11__0)*
	{ after(grammarAccess.getTalkAccess().getGroup_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__12__Impl
	rule__Talk__Group__13
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getRightParenthesisKeyword_12()); }
	')'
	{ after(grammarAccess.getTalkAccess().getRightParenthesisKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__13
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group__13__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group__13__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getRightCurlyBracketKeyword_13()); }
	'}'
	{ after(grammarAccess.getTalkAccess().getRightCurlyBracketKeyword_13()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Talk__Group_11__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group_11__0__Impl
	rule__Talk__Group_11__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group_11__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getCommaKeyword_11_0()); }
	','
	{ after(grammarAccess.getTalkAccess().getCommaKeyword_11_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group_11__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Talk__Group_11__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__Group_11__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTalkAccess().getPresentersAssignment_11_1()); }
	(rule__Talk__PresentersAssignment_11_1)
	{ after(grammarAccess.getTalkAccess().getPresentersAssignment_11_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Equipment__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Equipment__Group__0__Impl
	rule__Equipment__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEquipmentAccess().getEquipmentKeyword_0()); }
	'Equipment'
	{ after(grammarAccess.getEquipmentAccess().getEquipmentKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Equipment__Group__1__Impl
	rule__Equipment__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEquipmentAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getEquipmentAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Equipment__Group__2__Impl
	rule__Equipment__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEquipmentAccess().getEquipmentNameKeyword_2()); }
	'equipmentName'
	{ after(grammarAccess.getEquipmentAccess().getEquipmentNameKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Equipment__Group__3__Impl
	rule__Equipment__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEquipmentAccess().getEquipmentNameAssignment_3()); }
	(rule__Equipment__EquipmentNameAssignment_3)
	{ after(grammarAccess.getEquipmentAccess().getEquipmentNameAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Equipment__Group__4__Impl
	rule__Equipment__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEquipmentAccess().getGroup_4()); }
	(rule__Equipment__Group_4__0)?
	{ after(grammarAccess.getEquipmentAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Equipment__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEquipmentAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getEquipmentAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Equipment__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Equipment__Group_4__0__Impl
	rule__Equipment__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEquipmentAccess().getEquipmentTypeKeyword_4_0()); }
	'equipmentType'
	{ after(grammarAccess.getEquipmentAccess().getEquipmentTypeKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Equipment__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEquipmentAccess().getEquipmentTypeAssignment_4_1()); }
	(rule__Equipment__EquipmentTypeAssignment_4_1)
	{ after(grammarAccess.getEquipmentAccess().getEquipmentTypeAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Model__EventsAssignment_3_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getEventsEventParserRuleCall_3_2_0()); }
		ruleEvent
		{ after(grammarAccess.getModelAccess().getEventsEventParserRuleCall_3_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Model__EventsAssignment_3_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getEventsEventParserRuleCall_3_3_1_0()); }
		ruleEvent
		{ after(grammarAccess.getModelAccess().getEventsEventParserRuleCall_3_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__EventNameAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getEventNameEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getEventAccess().getEventNameEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__EventStartDateAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getEventStartDateEStringParserRuleCall_5_0()); }
		ruleEString
		{ after(grammarAccess.getEventAccess().getEventStartDateEStringParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__EventEndDateAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getEventEndDateEStringParserRuleCall_7_0()); }
		ruleEString
		{ after(grammarAccess.getEventAccess().getEventEndDateEStringParserRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__DescAssignment_8_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getDescEStringParserRuleCall_8_1_0()); }
		ruleEString
		{ after(grammarAccess.getEventAccess().getDescEStringParserRuleCall_8_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__PersonsAssignment_9_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_9_2_0()); }
		rulePerson
		{ after(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_9_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__PersonsAssignment_9_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_9_3_1_0()); }
		rulePerson
		{ after(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_9_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__ProgramItemsAssignment_10_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_10_2_0()); }
		ruleProgramItem
		{ after(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_10_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__ProgramItemsAssignment_10_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_10_3_1_0()); }
		ruleProgramItem
		{ after(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_10_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__LocationsAssignment_11_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_11_2_0()); }
		ruleLocation
		{ after(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_11_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__LocationsAssignment_11_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_11_3_1_0()); }
		ruleLocation
		{ after(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_11_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__PersonNameAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPersonAccess().getPersonNameEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getPersonAccess().getPersonNameEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__RolesAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_6_0()); }
		ruleRole
		{ after(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Person__RolesAssignment_7_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_7_1_0()); }
		ruleRole
		{ after(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_7_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__LocationNameAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLocationAccess().getLocationNameEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getLocationAccess().getLocationNameEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Location__LocationTypeAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLocationAccess().getLocationTypeLocationTypeEnumRuleCall_5_0()); }
		ruleLocationType
		{ after(grammarAccess.getLocationAccess().getLocationTypeLocationTypeEnumRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__SessionNameAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getSessionNameEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getSessionAccess().getSessionNameEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__StartTimeAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getStartTimeEStringParserRuleCall_5_0()); }
		ruleEString
		{ after(grammarAccess.getSessionAccess().getStartTimeEStringParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__EndTimeAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getEndTimeEStringParserRuleCall_7_0()); }
		ruleEString
		{ after(grammarAccess.getSessionAccess().getEndTimeEStringParserRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__LocationAssignment_9
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getLocationLocationCrossReference_9_0()); }
		(
			{ before(grammarAccess.getSessionAccess().getLocationLocationEStringParserRuleCall_9_0_1()); }
			ruleEString
			{ after(grammarAccess.getSessionAccess().getLocationLocationEStringParserRuleCall_9_0_1()); }
		)
		{ after(grammarAccess.getSessionAccess().getLocationLocationCrossReference_9_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__TechSupportAssignment_10_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_10_2_0()); }
		(
			{ before(grammarAccess.getSessionAccess().getTechSupportPersonEStringParserRuleCall_10_2_0_1()); }
			ruleEString
			{ after(grammarAccess.getSessionAccess().getTechSupportPersonEStringParserRuleCall_10_2_0_1()); }
		)
		{ after(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_10_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__TechSupportAssignment_10_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_10_3_1_0()); }
		(
			{ before(grammarAccess.getSessionAccess().getTechSupportPersonEStringParserRuleCall_10_3_1_0_1()); }
			ruleEString
			{ after(grammarAccess.getSessionAccess().getTechSupportPersonEStringParserRuleCall_10_3_1_0_1()); }
		)
		{ after(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_10_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__TalksAssignment_11_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_2_0()); }
		ruleTalk
		{ after(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__TalksAssignment_11_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_3_1_0()); }
		ruleTalk
		{ after(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__EquipmentAssignment_12_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_12_2_0()); }
		ruleEquipment
		{ after(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_12_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Session__EquipmentAssignment_12_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_12_3_1_0()); }
		ruleEquipment
		{ after(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_12_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__BreakNameAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getBreakNameEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getBreakAccess().getBreakNameEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__StartTimeAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getStartTimeEStringParserRuleCall_5_0()); }
		ruleEString
		{ after(grammarAccess.getBreakAccess().getStartTimeEStringParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__EndTimeAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getEndTimeEStringParserRuleCall_7_0()); }
		ruleEString
		{ after(grammarAccess.getBreakAccess().getEndTimeEStringParserRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__LocationAssignment_9
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getLocationLocationCrossReference_9_0()); }
		(
			{ before(grammarAccess.getBreakAccess().getLocationLocationEStringParserRuleCall_9_0_1()); }
			ruleEString
			{ after(grammarAccess.getBreakAccess().getLocationLocationEStringParserRuleCall_9_0_1()); }
		)
		{ after(grammarAccess.getBreakAccess().getLocationLocationCrossReference_9_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__AnimatorsAssignment_10_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_10_2_0()); }
		(
			{ before(grammarAccess.getBreakAccess().getAnimatorsPersonEStringParserRuleCall_10_2_0_1()); }
			ruleEString
			{ after(grammarAccess.getBreakAccess().getAnimatorsPersonEStringParserRuleCall_10_2_0_1()); }
		)
		{ after(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_10_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Break__AnimatorsAssignment_10_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_10_3_1_0()); }
		(
			{ before(grammarAccess.getBreakAccess().getAnimatorsPersonEStringParserRuleCall_10_3_1_0_1()); }
			ruleEString
			{ after(grammarAccess.getBreakAccess().getAnimatorsPersonEStringParserRuleCall_10_3_1_0_1()); }
		)
		{ after(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_10_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__TalkNameAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getTalkNameEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getTalkAccess().getTalkNameEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__TalkStartTimeAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getTalkStartTimeEStringParserRuleCall_5_0()); }
		ruleEString
		{ after(grammarAccess.getTalkAccess().getTalkStartTimeEStringParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__TalkEndTimeAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getTalkEndTimeEStringParserRuleCall_7_0()); }
		ruleEString
		{ after(grammarAccess.getTalkAccess().getTalkEndTimeEStringParserRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__PresentersAssignment_10
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_10_0()); }
		(
			{ before(grammarAccess.getTalkAccess().getPresentersPersonEStringParserRuleCall_10_0_1()); }
			ruleEString
			{ after(grammarAccess.getTalkAccess().getPresentersPersonEStringParserRuleCall_10_0_1()); }
		)
		{ after(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_10_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Talk__PresentersAssignment_11_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_11_1_0()); }
		(
			{ before(grammarAccess.getTalkAccess().getPresentersPersonEStringParserRuleCall_11_1_0_1()); }
			ruleEString
			{ after(grammarAccess.getTalkAccess().getPresentersPersonEStringParserRuleCall_11_1_0_1()); }
		)
		{ after(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_11_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__EquipmentNameAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEquipmentAccess().getEquipmentNameEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getEquipmentAccess().getEquipmentNameEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Equipment__EquipmentTypeAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEquipmentAccess().getEquipmentTypeEStringParserRuleCall_4_1_0()); }
		ruleEString
		{ after(grammarAccess.getEquipmentAccess().getEquipmentTypeEStringParserRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
