/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAgendomatScopeProvider extends DelegatingScopeProvider {
}
