/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class AgendomatGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEventKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEventNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEventNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cEventNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cFromKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cEventStartDateAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cEventStartDateSTRINGTerminalRuleCall_2_0_1_0 = (RuleCall)cEventStartDateAssignment_2_0_1.eContents().get(0);
		private final Keyword cToKeyword_2_0_2 = (Keyword)cGroup_2_0.eContents().get(2);
		private final Assignment cEventEndDateAssignment_2_0_3 = (Assignment)cGroup_2_0.eContents().get(3);
		private final RuleCall cEventEndDateSTRINGTerminalRuleCall_2_0_3_0 = (RuleCall)cEventEndDateAssignment_2_0_3.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cOnKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cEventStartDateAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cEventStartDateSTRINGTerminalRuleCall_2_1_1_0 = (RuleCall)cEventStartDateAssignment_2_1_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescAssignment_4_1.eContents().get(0);
		private final Assignment cPersonsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPersonsPersonParserRuleCall_5_0 = (RuleCall)cPersonsAssignment_5.eContents().get(0);
		private final Assignment cLocationsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLocationsLocationParserRuleCall_6_0 = (RuleCall)cLocationsAssignment_6.eContents().get(0);
		private final Assignment cProgramItemsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cProgramItemsProgramItemParserRuleCall_7_0 = (RuleCall)cProgramItemsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Event returns Event:
		//    'Event' eventName=STRING
		//    ('from' eventStartDate=STRING 'to' eventEndDate=STRING
		//    | 'on' eventStartDate=STRING)
		//    '{'
		//        ('Description' desc=STRING)?
		//        persons+=Person*
		//        locations+=Location*
		//        programItems+=ProgramItem*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Event' eventName=STRING
		//('from' eventStartDate=STRING 'to' eventEndDate=STRING
		//| 'on' eventStartDate=STRING)
		//'{'
		//    ('Description' desc=STRING)?
		//    persons+=Person*
		//    locations+=Location*
		//    programItems+=ProgramItem*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Event'
		public Keyword getEventKeyword_0() { return cEventKeyword_0; }
		
		//eventName=STRING
		public Assignment getEventNameAssignment_1() { return cEventNameAssignment_1; }
		
		//STRING
		public RuleCall getEventNameSTRINGTerminalRuleCall_1_0() { return cEventNameSTRINGTerminalRuleCall_1_0; }
		
		//('from' eventStartDate=STRING 'to' eventEndDate=STRING
		//| 'on' eventStartDate=STRING)
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//'from' eventStartDate=STRING 'to' eventEndDate=STRING
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'from'
		public Keyword getFromKeyword_2_0_0() { return cFromKeyword_2_0_0; }
		
		//eventStartDate=STRING
		public Assignment getEventStartDateAssignment_2_0_1() { return cEventStartDateAssignment_2_0_1; }
		
		//STRING
		public RuleCall getEventStartDateSTRINGTerminalRuleCall_2_0_1_0() { return cEventStartDateSTRINGTerminalRuleCall_2_0_1_0; }
		
		//'to'
		public Keyword getToKeyword_2_0_2() { return cToKeyword_2_0_2; }
		
		//eventEndDate=STRING
		public Assignment getEventEndDateAssignment_2_0_3() { return cEventEndDateAssignment_2_0_3; }
		
		//STRING
		public RuleCall getEventEndDateSTRINGTerminalRuleCall_2_0_3_0() { return cEventEndDateSTRINGTerminalRuleCall_2_0_3_0; }
		
		//'on' eventStartDate=STRING
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'on'
		public Keyword getOnKeyword_2_1_0() { return cOnKeyword_2_1_0; }
		
		//eventStartDate=STRING
		public Assignment getEventStartDateAssignment_2_1_1() { return cEventStartDateAssignment_2_1_1; }
		
		//STRING
		public RuleCall getEventStartDateSTRINGTerminalRuleCall_2_1_1_0() { return cEventStartDateSTRINGTerminalRuleCall_2_1_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('Description' desc=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//desc=STRING
		public Assignment getDescAssignment_4_1() { return cDescAssignment_4_1; }
		
		//STRING
		public RuleCall getDescSTRINGTerminalRuleCall_4_1_0() { return cDescSTRINGTerminalRuleCall_4_1_0; }
		
		//persons+=Person*
		public Assignment getPersonsAssignment_5() { return cPersonsAssignment_5; }
		
		//Person
		public RuleCall getPersonsPersonParserRuleCall_5_0() { return cPersonsPersonParserRuleCall_5_0; }
		
		//locations+=Location*
		public Assignment getLocationsAssignment_6() { return cLocationsAssignment_6; }
		
		//Location
		public RuleCall getLocationsLocationParserRuleCall_6_0() { return cLocationsLocationParserRuleCall_6_0; }
		
		//programItems+=ProgramItem*
		public Assignment getProgramItemsAssignment_7() { return cProgramItemsAssignment_7; }
		
		//ProgramItem
		public RuleCall getProgramItemsProgramItemParserRuleCall_7_0() { return cProgramItemsProgramItemParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ProgramItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.ProgramItem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSessionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBreakParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ProgramItem returns ProgramItem:
		//    Session | Break;
		@Override public ParserRule getRule() { return rule; }
		
		//Session | Break
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Session
		public RuleCall getSessionParserRuleCall_0() { return cSessionParserRuleCall_0; }
		
		//Break
		public RuleCall getBreakParserRuleCall_1() { return cBreakParserRuleCall_1; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.Person");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPersonNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPersonNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cPersonNameAssignment_1.eContents().get(0);
		private final Keyword cRolesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRolesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRolesRoleEnumRuleCall_4_0 = (RuleCall)cRolesAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRolesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRolesRoleEnumRuleCall_5_1_0 = (RuleCall)cRolesAssignment_5_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Person returns Person:
		//    'Person' personName=STRING 'roles' '[' roles+=Role (',' roles+=Role)* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'Person' personName=STRING 'roles' '[' roles+=Role (',' roles+=Role)* ']'
		public Group getGroup() { return cGroup; }
		
		//'Person'
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }
		
		//personName=STRING
		public Assignment getPersonNameAssignment_1() { return cPersonNameAssignment_1; }
		
		//STRING
		public RuleCall getPersonNameSTRINGTerminalRuleCall_1_0() { return cPersonNameSTRINGTerminalRuleCall_1_0; }
		
		//'roles'
		public Keyword getRolesKeyword_2() { return cRolesKeyword_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3() { return cLeftSquareBracketKeyword_3; }
		
		//roles+=Role
		public Assignment getRolesAssignment_4() { return cRolesAssignment_4; }
		
		//Role
		public RuleCall getRolesRoleEnumRuleCall_4_0() { return cRolesRoleEnumRuleCall_4_0; }
		
		//(',' roles+=Role)*
		public Group getGroup_5() { return cGroup_5; }
		
		//','
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//roles+=Role
		public Assignment getRolesAssignment_5_1() { return cRolesAssignment_5_1; }
		
		//Role
		public RuleCall getRolesRoleEnumRuleCall_5_1_0() { return cRolesRoleEnumRuleCall_5_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_6() { return cRightSquareBracketKeyword_6; }
	}
	public class LocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.Location");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLocationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLocationNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLocationNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cLocationNameAssignment_1.eContents().get(0);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLocationTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLocationTypeLocationTypeEnumRuleCall_3_0 = (RuleCall)cLocationTypeAssignment_3.eContents().get(0);
		
		//Location returns Location:
		//    'Location' locationName=STRING 'type' locationType=LocationType;
		@Override public ParserRule getRule() { return rule; }
		
		//'Location' locationName=STRING 'type' locationType=LocationType
		public Group getGroup() { return cGroup; }
		
		//'Location'
		public Keyword getLocationKeyword_0() { return cLocationKeyword_0; }
		
		//locationName=STRING
		public Assignment getLocationNameAssignment_1() { return cLocationNameAssignment_1; }
		
		//STRING
		public RuleCall getLocationNameSTRINGTerminalRuleCall_1_0() { return cLocationNameSTRINGTerminalRuleCall_1_0; }
		
		//'type'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//locationType=LocationType
		public Assignment getLocationTypeAssignment_3() { return cLocationTypeAssignment_3; }
		
		//LocationType
		public RuleCall getLocationTypeLocationTypeEnumRuleCall_3_0() { return cLocationTypeLocationTypeEnumRuleCall_3_0; }
	}
	public class SessionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.Session");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSessionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSessionNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSessionNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cSessionNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTimeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStartTimeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStartTimeSTRINGTerminalRuleCall_4_0 = (RuleCall)cStartTimeAssignment_4.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEndTimeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEndTimeSTRINGTerminalRuleCall_6_0 = (RuleCall)cEndTimeAssignment_6.eContents().get(0);
		private final Keyword cLocationKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cLocationAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cLocationLocationCrossReference_8_0 = (CrossReference)cLocationAssignment_8.eContents().get(0);
		private final RuleCall cLocationLocationSTRINGTerminalRuleCall_8_0_1 = (RuleCall)cLocationLocationCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cTechSupportKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cTechSupportAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final CrossReference cTechSupportPersonCrossReference_9_2_0 = (CrossReference)cTechSupportAssignment_9_2.eContents().get(0);
		private final RuleCall cTechSupportPersonSTRINGTerminalRuleCall_9_2_0_1 = (RuleCall)cTechSupportPersonCrossReference_9_2_0.eContents().get(1);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cTechSupportAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final CrossReference cTechSupportPersonCrossReference_9_3_1_0 = (CrossReference)cTechSupportAssignment_9_3_1.eContents().get(0);
		private final RuleCall cTechSupportPersonSTRINGTerminalRuleCall_9_3_1_0_1 = (RuleCall)cTechSupportPersonCrossReference_9_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cNeedsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cEquipmentAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cEquipmentEquipmentParserRuleCall_10_1_0 = (RuleCall)cEquipmentAssignment_10_1.eContents().get(0);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Keyword cCommaKeyword_10_2_0 = (Keyword)cGroup_10_2.eContents().get(0);
		private final Assignment cEquipmentAssignment_10_2_1 = (Assignment)cGroup_10_2.eContents().get(1);
		private final RuleCall cEquipmentEquipmentParserRuleCall_10_2_1_0 = (RuleCall)cEquipmentAssignment_10_2_1.eContents().get(0);
		private final Assignment cTalksAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cTalksTalkParserRuleCall_11_0 = (RuleCall)cTalksAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Session returns Session:
		//    'Session' sessionName=STRING '{'
		//        'Time' startTime=STRING '-' endTime=STRING
		//        'Location' location=[Location|STRING]
		//        ('TechSupport' '(' techSupport+=[Person|STRING] (',' techSupport+=[Person|STRING])* ')')?
		//        ('Needs' equipment+=Equipment (',' equipment+=Equipment)*)?
		//        talks+=Talk*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Session' sessionName=STRING '{'
		//    'Time' startTime=STRING '-' endTime=STRING
		//    'Location' location=[Location|STRING]
		//    ('TechSupport' '(' techSupport+=[Person|STRING] (',' techSupport+=[Person|STRING])* ')')?
		//    ('Needs' equipment+=Equipment (',' equipment+=Equipment)*)?
		//    talks+=Talk*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Session'
		public Keyword getSessionKeyword_0() { return cSessionKeyword_0; }
		
		//sessionName=STRING
		public Assignment getSessionNameAssignment_1() { return cSessionNameAssignment_1; }
		
		//STRING
		public RuleCall getSessionNameSTRINGTerminalRuleCall_1_0() { return cSessionNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'Time'
		public Keyword getTimeKeyword_3() { return cTimeKeyword_3; }
		
		//startTime=STRING
		public Assignment getStartTimeAssignment_4() { return cStartTimeAssignment_4; }
		
		//STRING
		public RuleCall getStartTimeSTRINGTerminalRuleCall_4_0() { return cStartTimeSTRINGTerminalRuleCall_4_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_5() { return cHyphenMinusKeyword_5; }
		
		//endTime=STRING
		public Assignment getEndTimeAssignment_6() { return cEndTimeAssignment_6; }
		
		//STRING
		public RuleCall getEndTimeSTRINGTerminalRuleCall_6_0() { return cEndTimeSTRINGTerminalRuleCall_6_0; }
		
		//'Location'
		public Keyword getLocationKeyword_7() { return cLocationKeyword_7; }
		
		//location=[Location|STRING]
		public Assignment getLocationAssignment_8() { return cLocationAssignment_8; }
		
		//[Location|STRING]
		public CrossReference getLocationLocationCrossReference_8_0() { return cLocationLocationCrossReference_8_0; }
		
		//STRING
		public RuleCall getLocationLocationSTRINGTerminalRuleCall_8_0_1() { return cLocationLocationSTRINGTerminalRuleCall_8_0_1; }
		
		//('TechSupport' '(' techSupport+=[Person|STRING] (',' techSupport+=[Person|STRING])* ')')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'TechSupport'
		public Keyword getTechSupportKeyword_9_0() { return cTechSupportKeyword_9_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_9_1() { return cLeftParenthesisKeyword_9_1; }
		
		//techSupport+=[Person|STRING]
		public Assignment getTechSupportAssignment_9_2() { return cTechSupportAssignment_9_2; }
		
		//[Person|STRING]
		public CrossReference getTechSupportPersonCrossReference_9_2_0() { return cTechSupportPersonCrossReference_9_2_0; }
		
		//STRING
		public RuleCall getTechSupportPersonSTRINGTerminalRuleCall_9_2_0_1() { return cTechSupportPersonSTRINGTerminalRuleCall_9_2_0_1; }
		
		//(',' techSupport+=[Person|STRING])*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//','
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//techSupport+=[Person|STRING]
		public Assignment getTechSupportAssignment_9_3_1() { return cTechSupportAssignment_9_3_1; }
		
		//[Person|STRING]
		public CrossReference getTechSupportPersonCrossReference_9_3_1_0() { return cTechSupportPersonCrossReference_9_3_1_0; }
		
		//STRING
		public RuleCall getTechSupportPersonSTRINGTerminalRuleCall_9_3_1_0_1() { return cTechSupportPersonSTRINGTerminalRuleCall_9_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9_4() { return cRightParenthesisKeyword_9_4; }
		
		//('Needs' equipment+=Equipment (',' equipment+=Equipment)*)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'Needs'
		public Keyword getNeedsKeyword_10_0() { return cNeedsKeyword_10_0; }
		
		//equipment+=Equipment
		public Assignment getEquipmentAssignment_10_1() { return cEquipmentAssignment_10_1; }
		
		//Equipment
		public RuleCall getEquipmentEquipmentParserRuleCall_10_1_0() { return cEquipmentEquipmentParserRuleCall_10_1_0; }
		
		//(',' equipment+=Equipment)*
		public Group getGroup_10_2() { return cGroup_10_2; }
		
		//','
		public Keyword getCommaKeyword_10_2_0() { return cCommaKeyword_10_2_0; }
		
		//equipment+=Equipment
		public Assignment getEquipmentAssignment_10_2_1() { return cEquipmentAssignment_10_2_1; }
		
		//Equipment
		public RuleCall getEquipmentEquipmentParserRuleCall_10_2_1_0() { return cEquipmentEquipmentParserRuleCall_10_2_1_0; }
		
		//talks+=Talk*
		public Assignment getTalksAssignment_11() { return cTalksAssignment_11; }
		
		//Talk
		public RuleCall getTalksTalkParserRuleCall_11_0() { return cTalksTalkParserRuleCall_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class BreakElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.Break");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBreakKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cBreakNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cBreakNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cBreakNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTimeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStartTimeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStartTimeSTRINGTerminalRuleCall_4_0 = (RuleCall)cStartTimeAssignment_4.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEndTimeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEndTimeSTRINGTerminalRuleCall_6_0 = (RuleCall)cEndTimeAssignment_6.eContents().get(0);
		private final Keyword cLocationKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cLocationAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cLocationLocationCrossReference_8_0 = (CrossReference)cLocationAssignment_8.eContents().get(0);
		private final RuleCall cLocationLocationSTRINGTerminalRuleCall_8_0_1 = (RuleCall)cLocationLocationCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cAnimatorKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cAnimatorsAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final CrossReference cAnimatorsPersonCrossReference_9_2_0 = (CrossReference)cAnimatorsAssignment_9_2.eContents().get(0);
		private final RuleCall cAnimatorsPersonSTRINGTerminalRuleCall_9_2_0_1 = (RuleCall)cAnimatorsPersonCrossReference_9_2_0.eContents().get(1);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cAnimatorsAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final CrossReference cAnimatorsPersonCrossReference_9_3_1_0 = (CrossReference)cAnimatorsAssignment_9_3_1.eContents().get(0);
		private final RuleCall cAnimatorsPersonSTRINGTerminalRuleCall_9_3_1_0_1 = (RuleCall)cAnimatorsPersonCrossReference_9_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Break returns Break:
		//    'Break' breakName=STRING '{'
		//        'Time' startTime=STRING '-' endTime=STRING
		//        'Location' location=[Location|STRING]
		//        ('Animator' '(' animators+=[Person|STRING] (',' animators+=[Person|STRING])* ')')?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Break' breakName=STRING '{'
		//    'Time' startTime=STRING '-' endTime=STRING
		//    'Location' location=[Location|STRING]
		//    ('Animator' '(' animators+=[Person|STRING] (',' animators+=[Person|STRING])* ')')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Break'
		public Keyword getBreakKeyword_0() { return cBreakKeyword_0; }
		
		//breakName=STRING
		public Assignment getBreakNameAssignment_1() { return cBreakNameAssignment_1; }
		
		//STRING
		public RuleCall getBreakNameSTRINGTerminalRuleCall_1_0() { return cBreakNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'Time'
		public Keyword getTimeKeyword_3() { return cTimeKeyword_3; }
		
		//startTime=STRING
		public Assignment getStartTimeAssignment_4() { return cStartTimeAssignment_4; }
		
		//STRING
		public RuleCall getStartTimeSTRINGTerminalRuleCall_4_0() { return cStartTimeSTRINGTerminalRuleCall_4_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_5() { return cHyphenMinusKeyword_5; }
		
		//endTime=STRING
		public Assignment getEndTimeAssignment_6() { return cEndTimeAssignment_6; }
		
		//STRING
		public RuleCall getEndTimeSTRINGTerminalRuleCall_6_0() { return cEndTimeSTRINGTerminalRuleCall_6_0; }
		
		//'Location'
		public Keyword getLocationKeyword_7() { return cLocationKeyword_7; }
		
		//location=[Location|STRING]
		public Assignment getLocationAssignment_8() { return cLocationAssignment_8; }
		
		//[Location|STRING]
		public CrossReference getLocationLocationCrossReference_8_0() { return cLocationLocationCrossReference_8_0; }
		
		//STRING
		public RuleCall getLocationLocationSTRINGTerminalRuleCall_8_0_1() { return cLocationLocationSTRINGTerminalRuleCall_8_0_1; }
		
		//('Animator' '(' animators+=[Person|STRING] (',' animators+=[Person|STRING])* ')')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'Animator'
		public Keyword getAnimatorKeyword_9_0() { return cAnimatorKeyword_9_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_9_1() { return cLeftParenthesisKeyword_9_1; }
		
		//animators+=[Person|STRING]
		public Assignment getAnimatorsAssignment_9_2() { return cAnimatorsAssignment_9_2; }
		
		//[Person|STRING]
		public CrossReference getAnimatorsPersonCrossReference_9_2_0() { return cAnimatorsPersonCrossReference_9_2_0; }
		
		//STRING
		public RuleCall getAnimatorsPersonSTRINGTerminalRuleCall_9_2_0_1() { return cAnimatorsPersonSTRINGTerminalRuleCall_9_2_0_1; }
		
		//(',' animators+=[Person|STRING])*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//','
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//animators+=[Person|STRING]
		public Assignment getAnimatorsAssignment_9_3_1() { return cAnimatorsAssignment_9_3_1; }
		
		//[Person|STRING]
		public CrossReference getAnimatorsPersonCrossReference_9_3_1_0() { return cAnimatorsPersonCrossReference_9_3_1_0; }
		
		//STRING
		public RuleCall getAnimatorsPersonSTRINGTerminalRuleCall_9_3_1_0_1() { return cAnimatorsPersonSTRINGTerminalRuleCall_9_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9_4() { return cRightParenthesisKeyword_9_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class TalkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.Talk");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTalkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTalkNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTalkNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cTalkNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTimeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTalkStartTimeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTalkStartTimeSTRINGTerminalRuleCall_4_0 = (RuleCall)cTalkStartTimeAssignment_4.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTalkEndTimeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTalkEndTimeSTRINGTerminalRuleCall_6_0 = (RuleCall)cTalkEndTimeAssignment_6.eContents().get(0);
		private final Keyword cPresenterKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cPresentersAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cPresentersPersonCrossReference_9_0 = (CrossReference)cPresentersAssignment_9.eContents().get(0);
		private final RuleCall cPresentersPersonSTRINGTerminalRuleCall_9_0_1 = (RuleCall)cPresentersPersonCrossReference_9_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cPresentersAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cPresentersPersonCrossReference_10_1_0 = (CrossReference)cPresentersAssignment_10_1.eContents().get(0);
		private final RuleCall cPresentersPersonSTRINGTerminalRuleCall_10_1_0_1 = (RuleCall)cPresentersPersonCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Talk returns Talk:
		//    'Talk' talkName=STRING '{'
		//        'Time' talkStartTime=STRING '-' talkEndTime=STRING
		//        'Presenter' '(' presenters+=[Person|STRING] (',' presenters+=[Person|STRING])* ')'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Talk' talkName=STRING '{'
		//    'Time' talkStartTime=STRING '-' talkEndTime=STRING
		//    'Presenter' '(' presenters+=[Person|STRING] (',' presenters+=[Person|STRING])* ')'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Talk'
		public Keyword getTalkKeyword_0() { return cTalkKeyword_0; }
		
		//talkName=STRING
		public Assignment getTalkNameAssignment_1() { return cTalkNameAssignment_1; }
		
		//STRING
		public RuleCall getTalkNameSTRINGTerminalRuleCall_1_0() { return cTalkNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'Time'
		public Keyword getTimeKeyword_3() { return cTimeKeyword_3; }
		
		//talkStartTime=STRING
		public Assignment getTalkStartTimeAssignment_4() { return cTalkStartTimeAssignment_4; }
		
		//STRING
		public RuleCall getTalkStartTimeSTRINGTerminalRuleCall_4_0() { return cTalkStartTimeSTRINGTerminalRuleCall_4_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_5() { return cHyphenMinusKeyword_5; }
		
		//talkEndTime=STRING
		public Assignment getTalkEndTimeAssignment_6() { return cTalkEndTimeAssignment_6; }
		
		//STRING
		public RuleCall getTalkEndTimeSTRINGTerminalRuleCall_6_0() { return cTalkEndTimeSTRINGTerminalRuleCall_6_0; }
		
		//'Presenter'
		public Keyword getPresenterKeyword_7() { return cPresenterKeyword_7; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_8() { return cLeftParenthesisKeyword_8; }
		
		//presenters+=[Person|STRING]
		public Assignment getPresentersAssignment_9() { return cPresentersAssignment_9; }
		
		//[Person|STRING]
		public CrossReference getPresentersPersonCrossReference_9_0() { return cPresentersPersonCrossReference_9_0; }
		
		//STRING
		public RuleCall getPresentersPersonSTRINGTerminalRuleCall_9_0_1() { return cPresentersPersonSTRINGTerminalRuleCall_9_0_1; }
		
		//(',' presenters+=[Person|STRING])*
		public Group getGroup_10() { return cGroup_10; }
		
		//','
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//presenters+=[Person|STRING]
		public Assignment getPresentersAssignment_10_1() { return cPresentersAssignment_10_1; }
		
		//[Person|STRING]
		public CrossReference getPresentersPersonCrossReference_10_1_0() { return cPresentersPersonCrossReference_10_1_0; }
		
		//STRING
		public RuleCall getPresentersPersonSTRINGTerminalRuleCall_10_1_0_1() { return cPresentersPersonSTRINGTerminalRuleCall_10_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_11() { return cRightParenthesisKeyword_11; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class EquipmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.Equipment");
		private final Assignment cEquipmentNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cEquipmentNameSTRINGTerminalRuleCall_0 = (RuleCall)cEquipmentNameAssignment.eContents().get(0);
		
		//Equipment returns Equipment:
		//    equipmentName=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//equipmentName=STRING
		public Assignment getEquipmentNameAssignment() { return cEquipmentNameAssignment; }
		
		//STRING
		public RuleCall getEquipmentNameSTRINGTerminalRuleCall_0() { return cEquipmentNameSTRINGTerminalRuleCall_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	public class RoleElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.Role");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPresenterEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPresenterPresenterKeyword_0_0 = (Keyword)cPresenterEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTechSupportEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTechSupportTechSupportKeyword_1_0 = (Keyword)cTechSupportEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAnimatorEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAnimatorAnimatorKeyword_2_0 = (Keyword)cAnimatorEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Role returns Role:
		//    Presenter = 'Presenter' | TechSupport = 'TechSupport' | Animator = 'Animator';
		public EnumRule getRule() { return rule; }
		
		//Presenter = 'Presenter' | TechSupport = 'TechSupport' | Animator = 'Animator'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Presenter = 'Presenter'
		public EnumLiteralDeclaration getPresenterEnumLiteralDeclaration_0() { return cPresenterEnumLiteralDeclaration_0; }
		
		//'Presenter'
		public Keyword getPresenterPresenterKeyword_0_0() { return cPresenterPresenterKeyword_0_0; }
		
		//TechSupport = 'TechSupport'
		public EnumLiteralDeclaration getTechSupportEnumLiteralDeclaration_1() { return cTechSupportEnumLiteralDeclaration_1; }
		
		//'TechSupport'
		public Keyword getTechSupportTechSupportKeyword_1_0() { return cTechSupportTechSupportKeyword_1_0; }
		
		//Animator = 'Animator'
		public EnumLiteralDeclaration getAnimatorEnumLiteralDeclaration_2() { return cAnimatorEnumLiteralDeclaration_2; }
		
		//'Animator'
		public Keyword getAnimatorAnimatorKeyword_2_0() { return cAnimatorAnimatorKeyword_2_0; }
	}
	public class LocationTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "agendomat.dsl.Agendomat.LocationType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cRoomEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cRoomRoomKeyword_0_0 = (Keyword)cRoomEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBreakAreaEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBreakAreaBreakAreaKeyword_1_0 = (Keyword)cBreakAreaEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum LocationType returns LocationType:
		//    Room = 'Room' | BreakArea = 'BreakArea';
		public EnumRule getRule() { return rule; }
		
		//Room = 'Room' | BreakArea = 'BreakArea'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Room = 'Room'
		public EnumLiteralDeclaration getRoomEnumLiteralDeclaration_0() { return cRoomEnumLiteralDeclaration_0; }
		
		//'Room'
		public Keyword getRoomRoomKeyword_0_0() { return cRoomRoomKeyword_0_0; }
		
		//BreakArea = 'BreakArea'
		public EnumLiteralDeclaration getBreakAreaEnumLiteralDeclaration_1() { return cBreakAreaEnumLiteralDeclaration_1; }
		
		//'BreakArea'
		public Keyword getBreakAreaBreakAreaKeyword_1_0() { return cBreakAreaBreakAreaKeyword_1_0; }
	}
	
	private final EventElements pEvent;
	private final ProgramItemElements pProgramItem;
	private final PersonElements pPerson;
	private final LocationElements pLocation;
	private final SessionElements pSession;
	private final BreakElements pBreak;
	private final TalkElements pTalk;
	private final EquipmentElements pEquipment;
	private final EStringElements pEString;
	private final RoleElements eRole;
	private final LocationTypeElements eLocationType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AgendomatGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pEvent = new EventElements();
		this.pProgramItem = new ProgramItemElements();
		this.pPerson = new PersonElements();
		this.pLocation = new LocationElements();
		this.pSession = new SessionElements();
		this.pBreak = new BreakElements();
		this.pTalk = new TalkElements();
		this.pEquipment = new EquipmentElements();
		this.pEString = new EStringElements();
		this.eRole = new RoleElements();
		this.eLocationType = new LocationTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("agendomat.dsl.Agendomat".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Event returns Event:
	//    'Event' eventName=STRING
	//    ('from' eventStartDate=STRING 'to' eventEndDate=STRING
	//    | 'on' eventStartDate=STRING)
	//    '{'
	//        ('Description' desc=STRING)?
	//        persons+=Person*
	//        locations+=Location*
	//        programItems+=ProgramItem*
	//    '}';
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//ProgramItem returns ProgramItem:
	//    Session | Break;
	public ProgramItemElements getProgramItemAccess() {
		return pProgramItem;
	}
	
	public ParserRule getProgramItemRule() {
		return getProgramItemAccess().getRule();
	}
	
	//Person returns Person:
	//    'Person' personName=STRING 'roles' '[' roles+=Role (',' roles+=Role)* ']';
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//Location returns Location:
	//    'Location' locationName=STRING 'type' locationType=LocationType;
	public LocationElements getLocationAccess() {
		return pLocation;
	}
	
	public ParserRule getLocationRule() {
		return getLocationAccess().getRule();
	}
	
	//Session returns Session:
	//    'Session' sessionName=STRING '{'
	//        'Time' startTime=STRING '-' endTime=STRING
	//        'Location' location=[Location|STRING]
	//        ('TechSupport' '(' techSupport+=[Person|STRING] (',' techSupport+=[Person|STRING])* ')')?
	//        ('Needs' equipment+=Equipment (',' equipment+=Equipment)*)?
	//        talks+=Talk*
	//    '}';
	public SessionElements getSessionAccess() {
		return pSession;
	}
	
	public ParserRule getSessionRule() {
		return getSessionAccess().getRule();
	}
	
	//Break returns Break:
	//    'Break' breakName=STRING '{'
	//        'Time' startTime=STRING '-' endTime=STRING
	//        'Location' location=[Location|STRING]
	//        ('Animator' '(' animators+=[Person|STRING] (',' animators+=[Person|STRING])* ')')?
	//    '}';
	public BreakElements getBreakAccess() {
		return pBreak;
	}
	
	public ParserRule getBreakRule() {
		return getBreakAccess().getRule();
	}
	
	//Talk returns Talk:
	//    'Talk' talkName=STRING '{'
	//        'Time' talkStartTime=STRING '-' talkEndTime=STRING
	//        'Presenter' '(' presenters+=[Person|STRING] (',' presenters+=[Person|STRING])* ')'
	//    '}';
	public TalkElements getTalkAccess() {
		return pTalk;
	}
	
	public ParserRule getTalkRule() {
		return getTalkAccess().getRule();
	}
	
	//Equipment returns Equipment:
	//    equipmentName=STRING;
	public EquipmentElements getEquipmentAccess() {
		return pEquipment;
	}
	
	public ParserRule getEquipmentRule() {
		return getEquipmentAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum Role returns Role:
	//    Presenter = 'Presenter' | TechSupport = 'TechSupport' | Animator = 'Animator';
	public RoleElements getRoleAccess() {
		return eRole;
	}
	
	public EnumRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//enum LocationType returns LocationType:
	//    Room = 'Room' | BreakArea = 'BreakArea';
	public LocationTypeElements getLocationTypeAccess() {
		return eLocationType;
	}
	
	public EnumRule getLocationTypeRule() {
		return getLocationTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
