/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.ide.contentassist.antlr;

import agendomat.dsl.ide.contentassist.antlr.internal.InternalAgendomatParser;
import agendomat.dsl.services.AgendomatGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AgendomatParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AgendomatGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AgendomatGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEventAccess().getAlternatives_2(), "rule__Event__Alternatives_2");
			builder.put(grammarAccess.getProgramItemAccess().getAlternatives(), "rule__ProgramItem__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getRoleAccess().getAlternatives(), "rule__Role__Alternatives");
			builder.put(grammarAccess.getLocationTypeAccess().getAlternatives(), "rule__LocationType__Alternatives");
			builder.put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup_2_0(), "rule__Event__Group_2_0__0");
			builder.put(grammarAccess.getEventAccess().getGroup_2_1(), "rule__Event__Group_2_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_4(), "rule__Event__Group_4__0");
			builder.put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
			builder.put(grammarAccess.getPersonAccess().getGroup_5(), "rule__Person__Group_5__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getSessionAccess().getGroup(), "rule__Session__Group__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_9(), "rule__Session__Group_9__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_9_3(), "rule__Session__Group_9_3__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_10(), "rule__Session__Group_10__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_10_2(), "rule__Session__Group_10_2__0");
			builder.put(grammarAccess.getBreakAccess().getGroup(), "rule__Break__Group__0");
			builder.put(grammarAccess.getBreakAccess().getGroup_9(), "rule__Break__Group_9__0");
			builder.put(grammarAccess.getBreakAccess().getGroup_9_3(), "rule__Break__Group_9_3__0");
			builder.put(grammarAccess.getTalkAccess().getGroup(), "rule__Talk__Group__0");
			builder.put(grammarAccess.getTalkAccess().getGroup_10(), "rule__Talk__Group_10__0");
			builder.put(grammarAccess.getEventAccess().getEventNameAssignment_1(), "rule__Event__EventNameAssignment_1");
			builder.put(grammarAccess.getEventAccess().getEventStartDateAssignment_2_0_1(), "rule__Event__EventStartDateAssignment_2_0_1");
			builder.put(grammarAccess.getEventAccess().getEventEndDateAssignment_2_0_3(), "rule__Event__EventEndDateAssignment_2_0_3");
			builder.put(grammarAccess.getEventAccess().getEventStartDateAssignment_2_1_1(), "rule__Event__EventStartDateAssignment_2_1_1");
			builder.put(grammarAccess.getEventAccess().getDescAssignment_4_1(), "rule__Event__DescAssignment_4_1");
			builder.put(grammarAccess.getEventAccess().getPersonsAssignment_5(), "rule__Event__PersonsAssignment_5");
			builder.put(grammarAccess.getEventAccess().getLocationsAssignment_6(), "rule__Event__LocationsAssignment_6");
			builder.put(grammarAccess.getEventAccess().getProgramItemsAssignment_7(), "rule__Event__ProgramItemsAssignment_7");
			builder.put(grammarAccess.getPersonAccess().getPersonNameAssignment_1(), "rule__Person__PersonNameAssignment_1");
			builder.put(grammarAccess.getPersonAccess().getRolesAssignment_4(), "rule__Person__RolesAssignment_4");
			builder.put(grammarAccess.getPersonAccess().getRolesAssignment_5_1(), "rule__Person__RolesAssignment_5_1");
			builder.put(grammarAccess.getLocationAccess().getLocationNameAssignment_1(), "rule__Location__LocationNameAssignment_1");
			builder.put(grammarAccess.getLocationAccess().getLocationTypeAssignment_3(), "rule__Location__LocationTypeAssignment_3");
			builder.put(grammarAccess.getSessionAccess().getSessionNameAssignment_1(), "rule__Session__SessionNameAssignment_1");
			builder.put(grammarAccess.getSessionAccess().getStartTimeAssignment_4(), "rule__Session__StartTimeAssignment_4");
			builder.put(grammarAccess.getSessionAccess().getEndTimeAssignment_6(), "rule__Session__EndTimeAssignment_6");
			builder.put(grammarAccess.getSessionAccess().getLocationAssignment_8(), "rule__Session__LocationAssignment_8");
			builder.put(grammarAccess.getSessionAccess().getTechSupportAssignment_9_2(), "rule__Session__TechSupportAssignment_9_2");
			builder.put(grammarAccess.getSessionAccess().getTechSupportAssignment_9_3_1(), "rule__Session__TechSupportAssignment_9_3_1");
			builder.put(grammarAccess.getSessionAccess().getEquipmentAssignment_10_1(), "rule__Session__EquipmentAssignment_10_1");
			builder.put(grammarAccess.getSessionAccess().getEquipmentAssignment_10_2_1(), "rule__Session__EquipmentAssignment_10_2_1");
			builder.put(grammarAccess.getSessionAccess().getTalksAssignment_11(), "rule__Session__TalksAssignment_11");
			builder.put(grammarAccess.getBreakAccess().getBreakNameAssignment_1(), "rule__Break__BreakNameAssignment_1");
			builder.put(grammarAccess.getBreakAccess().getStartTimeAssignment_4(), "rule__Break__StartTimeAssignment_4");
			builder.put(grammarAccess.getBreakAccess().getEndTimeAssignment_6(), "rule__Break__EndTimeAssignment_6");
			builder.put(grammarAccess.getBreakAccess().getLocationAssignment_8(), "rule__Break__LocationAssignment_8");
			builder.put(grammarAccess.getBreakAccess().getAnimatorsAssignment_9_2(), "rule__Break__AnimatorsAssignment_9_2");
			builder.put(grammarAccess.getBreakAccess().getAnimatorsAssignment_9_3_1(), "rule__Break__AnimatorsAssignment_9_3_1");
			builder.put(grammarAccess.getTalkAccess().getTalkNameAssignment_1(), "rule__Talk__TalkNameAssignment_1");
			builder.put(grammarAccess.getTalkAccess().getTalkStartTimeAssignment_4(), "rule__Talk__TalkStartTimeAssignment_4");
			builder.put(grammarAccess.getTalkAccess().getTalkEndTimeAssignment_6(), "rule__Talk__TalkEndTimeAssignment_6");
			builder.put(grammarAccess.getTalkAccess().getPresentersAssignment_9(), "rule__Talk__PresentersAssignment_9");
			builder.put(grammarAccess.getTalkAccess().getPresentersAssignment_10_1(), "rule__Talk__PresentersAssignment_10_1");
			builder.put(grammarAccess.getEquipmentAccess().getEquipmentNameAssignment(), "rule__Equipment__EquipmentNameAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AgendomatGrammarAccess grammarAccess;

	@Override
	protected InternalAgendomatParser createParser() {
		InternalAgendomatParser result = new InternalAgendomatParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AgendomatGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AgendomatGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
