/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.ide.contentassist.antlr;

import agendomat.dsl.ide.contentassist.antlr.internal.InternalAgendomatParser;
import agendomat.dsl.services.AgendomatGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AgendomatParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AgendomatGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AgendomatGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getProgramItemAccess().getAlternatives(), "rule__ProgramItem__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getRoleAccess().getAlternatives(), "rule__Role__Alternatives");
			builder.put(grammarAccess.getLocationTypeAccess().getAlternatives(), "rule__LocationType__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_3(), "rule__Model__Group_3__0");
			builder.put(grammarAccess.getModelAccess().getGroup_3_3(), "rule__Model__Group_3_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup_8(), "rule__Event__Group_8__0");
			builder.put(grammarAccess.getEventAccess().getGroup_9(), "rule__Event__Group_9__0");
			builder.put(grammarAccess.getEventAccess().getGroup_9_3(), "rule__Event__Group_9_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_10(), "rule__Event__Group_10__0");
			builder.put(grammarAccess.getEventAccess().getGroup_10_3(), "rule__Event__Group_10_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_11(), "rule__Event__Group_11__0");
			builder.put(grammarAccess.getEventAccess().getGroup_11_3(), "rule__Event__Group_11_3__0");
			builder.put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
			builder.put(grammarAccess.getPersonAccess().getGroup_7(), "rule__Person__Group_7__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getSessionAccess().getGroup(), "rule__Session__Group__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_10(), "rule__Session__Group_10__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_10_3(), "rule__Session__Group_10_3__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_11(), "rule__Session__Group_11__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_11_3(), "rule__Session__Group_11_3__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_12(), "rule__Session__Group_12__0");
			builder.put(grammarAccess.getSessionAccess().getGroup_12_3(), "rule__Session__Group_12_3__0");
			builder.put(grammarAccess.getBreakAccess().getGroup(), "rule__Break__Group__0");
			builder.put(grammarAccess.getBreakAccess().getGroup_10(), "rule__Break__Group_10__0");
			builder.put(grammarAccess.getBreakAccess().getGroup_10_3(), "rule__Break__Group_10_3__0");
			builder.put(grammarAccess.getTalkAccess().getGroup(), "rule__Talk__Group__0");
			builder.put(grammarAccess.getTalkAccess().getGroup_11(), "rule__Talk__Group_11__0");
			builder.put(grammarAccess.getEquipmentAccess().getGroup(), "rule__Equipment__Group__0");
			builder.put(grammarAccess.getEquipmentAccess().getGroup_4(), "rule__Equipment__Group_4__0");
			builder.put(grammarAccess.getModelAccess().getEventsAssignment_3_2(), "rule__Model__EventsAssignment_3_2");
			builder.put(grammarAccess.getModelAccess().getEventsAssignment_3_3_1(), "rule__Model__EventsAssignment_3_3_1");
			builder.put(grammarAccess.getEventAccess().getEventNameAssignment_3(), "rule__Event__EventNameAssignment_3");
			builder.put(grammarAccess.getEventAccess().getEventStartDateAssignment_5(), "rule__Event__EventStartDateAssignment_5");
			builder.put(grammarAccess.getEventAccess().getEventEndDateAssignment_7(), "rule__Event__EventEndDateAssignment_7");
			builder.put(grammarAccess.getEventAccess().getDescAssignment_8_1(), "rule__Event__DescAssignment_8_1");
			builder.put(grammarAccess.getEventAccess().getPersonsAssignment_9_2(), "rule__Event__PersonsAssignment_9_2");
			builder.put(grammarAccess.getEventAccess().getPersonsAssignment_9_3_1(), "rule__Event__PersonsAssignment_9_3_1");
			builder.put(grammarAccess.getEventAccess().getProgramItemsAssignment_10_2(), "rule__Event__ProgramItemsAssignment_10_2");
			builder.put(grammarAccess.getEventAccess().getProgramItemsAssignment_10_3_1(), "rule__Event__ProgramItemsAssignment_10_3_1");
			builder.put(grammarAccess.getEventAccess().getLocationsAssignment_11_2(), "rule__Event__LocationsAssignment_11_2");
			builder.put(grammarAccess.getEventAccess().getLocationsAssignment_11_3_1(), "rule__Event__LocationsAssignment_11_3_1");
			builder.put(grammarAccess.getPersonAccess().getPersonNameAssignment_3(), "rule__Person__PersonNameAssignment_3");
			builder.put(grammarAccess.getPersonAccess().getRolesAssignment_6(), "rule__Person__RolesAssignment_6");
			builder.put(grammarAccess.getPersonAccess().getRolesAssignment_7_1(), "rule__Person__RolesAssignment_7_1");
			builder.put(grammarAccess.getLocationAccess().getLocationNameAssignment_3(), "rule__Location__LocationNameAssignment_3");
			builder.put(grammarAccess.getLocationAccess().getLocationTypeAssignment_5(), "rule__Location__LocationTypeAssignment_5");
			builder.put(grammarAccess.getSessionAccess().getSessionNameAssignment_3(), "rule__Session__SessionNameAssignment_3");
			builder.put(grammarAccess.getSessionAccess().getStartTimeAssignment_5(), "rule__Session__StartTimeAssignment_5");
			builder.put(grammarAccess.getSessionAccess().getEndTimeAssignment_7(), "rule__Session__EndTimeAssignment_7");
			builder.put(grammarAccess.getSessionAccess().getLocationAssignment_9(), "rule__Session__LocationAssignment_9");
			builder.put(grammarAccess.getSessionAccess().getTechSupportAssignment_10_2(), "rule__Session__TechSupportAssignment_10_2");
			builder.put(grammarAccess.getSessionAccess().getTechSupportAssignment_10_3_1(), "rule__Session__TechSupportAssignment_10_3_1");
			builder.put(grammarAccess.getSessionAccess().getTalksAssignment_11_2(), "rule__Session__TalksAssignment_11_2");
			builder.put(grammarAccess.getSessionAccess().getTalksAssignment_11_3_1(), "rule__Session__TalksAssignment_11_3_1");
			builder.put(grammarAccess.getSessionAccess().getEquipmentAssignment_12_2(), "rule__Session__EquipmentAssignment_12_2");
			builder.put(grammarAccess.getSessionAccess().getEquipmentAssignment_12_3_1(), "rule__Session__EquipmentAssignment_12_3_1");
			builder.put(grammarAccess.getBreakAccess().getBreakNameAssignment_3(), "rule__Break__BreakNameAssignment_3");
			builder.put(grammarAccess.getBreakAccess().getStartTimeAssignment_5(), "rule__Break__StartTimeAssignment_5");
			builder.put(grammarAccess.getBreakAccess().getEndTimeAssignment_7(), "rule__Break__EndTimeAssignment_7");
			builder.put(grammarAccess.getBreakAccess().getLocationAssignment_9(), "rule__Break__LocationAssignment_9");
			builder.put(grammarAccess.getBreakAccess().getAnimatorsAssignment_10_2(), "rule__Break__AnimatorsAssignment_10_2");
			builder.put(grammarAccess.getBreakAccess().getAnimatorsAssignment_10_3_1(), "rule__Break__AnimatorsAssignment_10_3_1");
			builder.put(grammarAccess.getTalkAccess().getTalkNameAssignment_3(), "rule__Talk__TalkNameAssignment_3");
			builder.put(grammarAccess.getTalkAccess().getTalkStartTimeAssignment_5(), "rule__Talk__TalkStartTimeAssignment_5");
			builder.put(grammarAccess.getTalkAccess().getTalkEndTimeAssignment_7(), "rule__Talk__TalkEndTimeAssignment_7");
			builder.put(grammarAccess.getTalkAccess().getPresentersAssignment_10(), "rule__Talk__PresentersAssignment_10");
			builder.put(grammarAccess.getTalkAccess().getPresentersAssignment_11_1(), "rule__Talk__PresentersAssignment_11_1");
			builder.put(grammarAccess.getEquipmentAccess().getEquipmentNameAssignment_3(), "rule__Equipment__EquipmentNameAssignment_3");
			builder.put(grammarAccess.getEquipmentAccess().getEquipmentTypeAssignment_4_1(), "rule__Equipment__EquipmentTypeAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AgendomatGrammarAccess grammarAccess;

	@Override
	protected InternalAgendomatParser createParser() {
		InternalAgendomatParser result = new InternalAgendomatParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AgendomatGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AgendomatGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
