/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.ide;

import agendomat.dsl.AgendomatRuntimeModule;
import agendomat.dsl.AgendomatStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AgendomatIdeSetup extends AgendomatStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AgendomatRuntimeModule(), new AgendomatIdeModule()));
	}
	
}
