/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AgendomatStandaloneSetup extends AgendomatStandaloneSetupGenerated {

	public static void doSetup() {
		new AgendomatStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
