grammar agendomat.dsl.Agendomat with org.eclipse.xtext.common.Terminals

import "http://agendomat/1.0"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Event returns Event:
    'Event' eventName=STRING
    ('from' eventStartDate=STRING 'to' eventEndDate=STRING
    | 'on' eventStartDate=STRING)
    '{'
        ('Description' desc=STRING)?
        persons+=Person*
        locations+=Location*
        programItems+=ProgramItem*
    '}';

ProgramItem returns ProgramItem:
    Session | Break;

Person returns Person:
    'Person' personName=STRING 'roles' '[' roles+=Role (',' roles+=Role)* ']';

Location returns Location:
    'Location' locationName=STRING 'type' locationType=LocationType;

Session returns Session:
    'Session' sessionName=STRING '{'
        'Time' startTime=STRING '-' endTime=STRING
        'Location' location=[Location|STRING]
        ('TechSupport' '(' techSupport+=[Person|STRING] (',' techSupport+=[Person|STRING])* ')')?
        ('Needs' equipment+=Equipment (',' equipment+=Equipment)*)?
        talks+=Talk*
    '}';

Break returns Break:
    'Break' breakName=STRING '{'
        'Time' startTime=STRING '-' endTime=STRING
        'Location' location=[Location|STRING]
        ('Animator' '(' animators+=[Person|STRING] (',' animators+=[Person|STRING])* ')')?
    '}';

Talk returns Talk:
    'Talk' talkName=STRING '{'
        'Time' talkStartTime=STRING '-' talkEndTime=STRING
        'Presenter' '(' presenters+=[Person|STRING] (',' presenters+=[Person|STRING])* ')'
    '}';

Equipment returns Equipment:
    equipmentName=STRING;

EString returns ecore::EString:
    STRING | ID;

enum Role returns Role:
    Presenter = 'Presenter' | TechSupport = 'TechSupport' | Animator = 'Animator';

enum LocationType returns LocationType:
    Room = 'Room' | BreakArea = 'BreakArea';