/*
 * generated by Xtext 2.42.0
 */
grammar InternalAgendomat;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package agendomat.dsl.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package agendomat.dsl.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import agendomat.dsl.services.AgendomatGrammarAccess;

}

@parser::members {

 	private AgendomatGrammarAccess grammarAccess;

    public InternalAgendomatParser(TokenStream input, AgendomatGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Event";
   	}

   	@Override
   	protected AgendomatGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleEvent
entryRuleEvent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEventRule()); }
	iv_ruleEvent=ruleEvent
	{ $current=$iv_ruleEvent.current; }
	EOF;

// Rule Event
ruleEvent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Event'
		{
			newLeafNode(otherlv_0, grammarAccess.getEventAccess().getEventKeyword_0());
		}
		(
			(
				lv_eventName_1_0=RULE_STRING
				{
					newLeafNode(lv_eventName_1_0, grammarAccess.getEventAccess().getEventNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getEventRule());
					}
					setWithLastConsumed(
						$current,
						"eventName",
						lv_eventName_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		(
			(
				otherlv_2='from'
				{
					newLeafNode(otherlv_2, grammarAccess.getEventAccess().getFromKeyword_2_0_0());
				}
				(
					(
						lv_eventStartDate_3_0=RULE_STRING
						{
							newLeafNode(lv_eventStartDate_3_0, grammarAccess.getEventAccess().getEventStartDateSTRINGTerminalRuleCall_2_0_1_0());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getEventRule());
							}
							setWithLastConsumed(
								$current,
								"eventStartDate",
								lv_eventStartDate_3_0,
								"org.eclipse.xtext.common.Terminals.STRING");
						}
					)
				)
				otherlv_4='to'
				{
					newLeafNode(otherlv_4, grammarAccess.getEventAccess().getToKeyword_2_0_2());
				}
				(
					(
						lv_eventEndDate_5_0=RULE_STRING
						{
							newLeafNode(lv_eventEndDate_5_0, grammarAccess.getEventAccess().getEventEndDateSTRINGTerminalRuleCall_2_0_3_0());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getEventRule());
							}
							setWithLastConsumed(
								$current,
								"eventEndDate",
								lv_eventEndDate_5_0,
								"org.eclipse.xtext.common.Terminals.STRING");
						}
					)
				)
			)
			    |
			(
				otherlv_6='on'
				{
					newLeafNode(otherlv_6, grammarAccess.getEventAccess().getOnKeyword_2_1_0());
				}
				(
					(
						lv_eventStartDate_7_0=RULE_STRING
						{
							newLeafNode(lv_eventStartDate_7_0, grammarAccess.getEventAccess().getEventStartDateSTRINGTerminalRuleCall_2_1_1_0());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getEventRule());
							}
							setWithLastConsumed(
								$current,
								"eventStartDate",
								lv_eventStartDate_7_0,
								"org.eclipse.xtext.common.Terminals.STRING");
						}
					)
				)
			)
		)
		otherlv_8='{'
		{
			newLeafNode(otherlv_8, grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			otherlv_9='Description'
			{
				newLeafNode(otherlv_9, grammarAccess.getEventAccess().getDescriptionKeyword_4_0());
			}
			(
				(
					lv_desc_10_0=RULE_STRING
					{
						newLeafNode(lv_desc_10_0, grammarAccess.getEventAccess().getDescSTRINGTerminalRuleCall_4_1_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getEventRule());
						}
						setWithLastConsumed(
							$current,
							"desc",
							lv_desc_10_0,
							"org.eclipse.xtext.common.Terminals.STRING");
					}
				)
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_5_0());
				}
				lv_persons_11_0=rulePerson
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventRule());
					}
					add(
						$current,
						"persons",
						lv_persons_11_0,
						"agendomat.dsl.Agendomat.Person");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_6_0());
				}
				lv_locations_12_0=ruleLocation
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventRule());
					}
					add(
						$current,
						"locations",
						lv_locations_12_0,
						"agendomat.dsl.Agendomat.Location");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_7_0());
				}
				lv_programItems_13_0=ruleProgramItem
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventRule());
					}
					add(
						$current,
						"programItems",
						lv_programItems_13_0,
						"agendomat.dsl.Agendomat.ProgramItem");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_14='}'
		{
			newLeafNode(otherlv_14, grammarAccess.getEventAccess().getRightCurlyBracketKeyword_8());
		}
	)
;

// Entry rule entryRuleProgramItem
entryRuleProgramItem returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getProgramItemRule()); }
	iv_ruleProgramItem=ruleProgramItem
	{ $current=$iv_ruleProgramItem.current; }
	EOF;

// Rule ProgramItem
ruleProgramItem returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getProgramItemAccess().getSessionParserRuleCall_0());
		}
		this_Session_0=ruleSession
		{
			$current = $this_Session_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getProgramItemAccess().getBreakParserRuleCall_1());
		}
		this_Break_1=ruleBreak
		{
			$current = $this_Break_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRulePerson
entryRulePerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonRule()); }
	iv_rulePerson=rulePerson
	{ $current=$iv_rulePerson.current; }
	EOF;

// Rule Person
rulePerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Person'
		{
			newLeafNode(otherlv_0, grammarAccess.getPersonAccess().getPersonKeyword_0());
		}
		(
			(
				lv_personName_1_0=RULE_STRING
				{
					newLeafNode(lv_personName_1_0, grammarAccess.getPersonAccess().getPersonNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPersonRule());
					}
					setWithLastConsumed(
						$current,
						"personName",
						lv_personName_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_2='roles'
		{
			newLeafNode(otherlv_2, grammarAccess.getPersonAccess().getRolesKeyword_2());
		}
		otherlv_3='['
		{
			newLeafNode(otherlv_3, grammarAccess.getPersonAccess().getLeftSquareBracketKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_4_0());
				}
				lv_roles_4_0=ruleRole
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPersonRule());
					}
					add(
						$current,
						"roles",
						lv_roles_4_0,
						"agendomat.dsl.Agendomat.Role");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_5=','
			{
				newLeafNode(otherlv_5, grammarAccess.getPersonAccess().getCommaKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_5_1_0());
					}
					lv_roles_6_0=ruleRole
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPersonRule());
						}
						add(
							$current,
							"roles",
							lv_roles_6_0,
							"agendomat.dsl.Agendomat.Role");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_7=']'
		{
			newLeafNode(otherlv_7, grammarAccess.getPersonAccess().getRightSquareBracketKeyword_6());
		}
	)
;

// Entry rule entryRuleLocation
entryRuleLocation returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLocationRule()); }
	iv_ruleLocation=ruleLocation
	{ $current=$iv_ruleLocation.current; }
	EOF;

// Rule Location
ruleLocation returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Location'
		{
			newLeafNode(otherlv_0, grammarAccess.getLocationAccess().getLocationKeyword_0());
		}
		(
			(
				lv_locationName_1_0=RULE_STRING
				{
					newLeafNode(lv_locationName_1_0, grammarAccess.getLocationAccess().getLocationNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getLocationRule());
					}
					setWithLastConsumed(
						$current,
						"locationName",
						lv_locationName_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_2='type'
		{
			newLeafNode(otherlv_2, grammarAccess.getLocationAccess().getTypeKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLocationAccess().getLocationTypeLocationTypeEnumRuleCall_3_0());
				}
				lv_locationType_3_0=ruleLocationType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLocationRule());
					}
					set(
						$current,
						"locationType",
						lv_locationType_3_0,
						"agendomat.dsl.Agendomat.LocationType");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleSession
entryRuleSession returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSessionRule()); }
	iv_ruleSession=ruleSession
	{ $current=$iv_ruleSession.current; }
	EOF;

// Rule Session
ruleSession returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Session'
		{
			newLeafNode(otherlv_0, grammarAccess.getSessionAccess().getSessionKeyword_0());
		}
		(
			(
				lv_sessionName_1_0=RULE_STRING
				{
					newLeafNode(lv_sessionName_1_0, grammarAccess.getSessionAccess().getSessionNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSessionRule());
					}
					setWithLastConsumed(
						$current,
						"sessionName",
						lv_sessionName_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='Time'
		{
			newLeafNode(otherlv_3, grammarAccess.getSessionAccess().getTimeKeyword_3());
		}
		(
			(
				lv_startTime_4_0=RULE_STRING
				{
					newLeafNode(lv_startTime_4_0, grammarAccess.getSessionAccess().getStartTimeSTRINGTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSessionRule());
					}
					setWithLastConsumed(
						$current,
						"startTime",
						lv_startTime_4_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_5='-'
		{
			newLeafNode(otherlv_5, grammarAccess.getSessionAccess().getHyphenMinusKeyword_5());
		}
		(
			(
				lv_endTime_6_0=RULE_STRING
				{
					newLeafNode(lv_endTime_6_0, grammarAccess.getSessionAccess().getEndTimeSTRINGTerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSessionRule());
					}
					setWithLastConsumed(
						$current,
						"endTime",
						lv_endTime_6_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_7='Location'
		{
			newLeafNode(otherlv_7, grammarAccess.getSessionAccess().getLocationKeyword_7());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSessionRule());
					}
				}
				otherlv_8=RULE_STRING
				{
					newLeafNode(otherlv_8, grammarAccess.getSessionAccess().getLocationLocationCrossReference_8_0());
				}
			)
		)
		(
			otherlv_9='TechSupport'
			{
				newLeafNode(otherlv_9, grammarAccess.getSessionAccess().getTechSupportKeyword_9_0());
			}
			otherlv_10='('
			{
				newLeafNode(otherlv_10, grammarAccess.getSessionAccess().getLeftParenthesisKeyword_9_1());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getSessionRule());
						}
					}
					otherlv_11=RULE_STRING
					{
						newLeafNode(otherlv_11, grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_9_2_0());
					}
				)
			)
			(
				otherlv_12=','
				{
					newLeafNode(otherlv_12, grammarAccess.getSessionAccess().getCommaKeyword_9_3_0());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getSessionRule());
							}
						}
						otherlv_13=RULE_STRING
						{
							newLeafNode(otherlv_13, grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_9_3_1_0());
						}
					)
				)
			)*
			otherlv_14=')'
			{
				newLeafNode(otherlv_14, grammarAccess.getSessionAccess().getRightParenthesisKeyword_9_4());
			}
		)?
		(
			otherlv_15='Needs'
			{
				newLeafNode(otherlv_15, grammarAccess.getSessionAccess().getNeedsKeyword_10_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_10_1_0());
					}
					lv_equipment_16_0=ruleEquipment
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSessionRule());
						}
						add(
							$current,
							"equipment",
							lv_equipment_16_0,
							"agendomat.dsl.Agendomat.Equipment");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_17=','
				{
					newLeafNode(otherlv_17, grammarAccess.getSessionAccess().getCommaKeyword_10_2_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_10_2_1_0());
						}
						lv_equipment_18_0=ruleEquipment
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getSessionRule());
							}
							add(
								$current,
								"equipment",
								lv_equipment_18_0,
								"agendomat.dsl.Agendomat.Equipment");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_0());
				}
				lv_talks_19_0=ruleTalk
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSessionRule());
					}
					add(
						$current,
						"talks",
						lv_talks_19_0,
						"agendomat.dsl.Agendomat.Talk");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_20='}'
		{
			newLeafNode(otherlv_20, grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_12());
		}
	)
;

// Entry rule entryRuleBreak
entryRuleBreak returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBreakRule()); }
	iv_ruleBreak=ruleBreak
	{ $current=$iv_ruleBreak.current; }
	EOF;

// Rule Break
ruleBreak returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Break'
		{
			newLeafNode(otherlv_0, grammarAccess.getBreakAccess().getBreakKeyword_0());
		}
		(
			(
				lv_breakName_1_0=RULE_STRING
				{
					newLeafNode(lv_breakName_1_0, grammarAccess.getBreakAccess().getBreakNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBreakRule());
					}
					setWithLastConsumed(
						$current,
						"breakName",
						lv_breakName_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getBreakAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='Time'
		{
			newLeafNode(otherlv_3, grammarAccess.getBreakAccess().getTimeKeyword_3());
		}
		(
			(
				lv_startTime_4_0=RULE_STRING
				{
					newLeafNode(lv_startTime_4_0, grammarAccess.getBreakAccess().getStartTimeSTRINGTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBreakRule());
					}
					setWithLastConsumed(
						$current,
						"startTime",
						lv_startTime_4_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_5='-'
		{
			newLeafNode(otherlv_5, grammarAccess.getBreakAccess().getHyphenMinusKeyword_5());
		}
		(
			(
				lv_endTime_6_0=RULE_STRING
				{
					newLeafNode(lv_endTime_6_0, grammarAccess.getBreakAccess().getEndTimeSTRINGTerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBreakRule());
					}
					setWithLastConsumed(
						$current,
						"endTime",
						lv_endTime_6_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_7='Location'
		{
			newLeafNode(otherlv_7, grammarAccess.getBreakAccess().getLocationKeyword_7());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBreakRule());
					}
				}
				otherlv_8=RULE_STRING
				{
					newLeafNode(otherlv_8, grammarAccess.getBreakAccess().getLocationLocationCrossReference_8_0());
				}
			)
		)
		(
			otherlv_9='Animator'
			{
				newLeafNode(otherlv_9, grammarAccess.getBreakAccess().getAnimatorKeyword_9_0());
			}
			otherlv_10='('
			{
				newLeafNode(otherlv_10, grammarAccess.getBreakAccess().getLeftParenthesisKeyword_9_1());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getBreakRule());
						}
					}
					otherlv_11=RULE_STRING
					{
						newLeafNode(otherlv_11, grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_9_2_0());
					}
				)
			)
			(
				otherlv_12=','
				{
					newLeafNode(otherlv_12, grammarAccess.getBreakAccess().getCommaKeyword_9_3_0());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getBreakRule());
							}
						}
						otherlv_13=RULE_STRING
						{
							newLeafNode(otherlv_13, grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_9_3_1_0());
						}
					)
				)
			)*
			otherlv_14=')'
			{
				newLeafNode(otherlv_14, grammarAccess.getBreakAccess().getRightParenthesisKeyword_9_4());
			}
		)?
		otherlv_15='}'
		{
			newLeafNode(otherlv_15, grammarAccess.getBreakAccess().getRightCurlyBracketKeyword_10());
		}
	)
;

// Entry rule entryRuleTalk
entryRuleTalk returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTalkRule()); }
	iv_ruleTalk=ruleTalk
	{ $current=$iv_ruleTalk.current; }
	EOF;

// Rule Talk
ruleTalk returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Talk'
		{
			newLeafNode(otherlv_0, grammarAccess.getTalkAccess().getTalkKeyword_0());
		}
		(
			(
				lv_talkName_1_0=RULE_STRING
				{
					newLeafNode(lv_talkName_1_0, grammarAccess.getTalkAccess().getTalkNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTalkRule());
					}
					setWithLastConsumed(
						$current,
						"talkName",
						lv_talkName_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getTalkAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='Time'
		{
			newLeafNode(otherlv_3, grammarAccess.getTalkAccess().getTimeKeyword_3());
		}
		(
			(
				lv_talkStartTime_4_0=RULE_STRING
				{
					newLeafNode(lv_talkStartTime_4_0, grammarAccess.getTalkAccess().getTalkStartTimeSTRINGTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTalkRule());
					}
					setWithLastConsumed(
						$current,
						"talkStartTime",
						lv_talkStartTime_4_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_5='-'
		{
			newLeafNode(otherlv_5, grammarAccess.getTalkAccess().getHyphenMinusKeyword_5());
		}
		(
			(
				lv_talkEndTime_6_0=RULE_STRING
				{
					newLeafNode(lv_talkEndTime_6_0, grammarAccess.getTalkAccess().getTalkEndTimeSTRINGTerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTalkRule());
					}
					setWithLastConsumed(
						$current,
						"talkEndTime",
						lv_talkEndTime_6_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_7='Presenter'
		{
			newLeafNode(otherlv_7, grammarAccess.getTalkAccess().getPresenterKeyword_7());
		}
		otherlv_8='('
		{
			newLeafNode(otherlv_8, grammarAccess.getTalkAccess().getLeftParenthesisKeyword_8());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTalkRule());
					}
				}
				otherlv_9=RULE_STRING
				{
					newLeafNode(otherlv_9, grammarAccess.getTalkAccess().getPresentersPersonCrossReference_9_0());
				}
			)
		)
		(
			otherlv_10=','
			{
				newLeafNode(otherlv_10, grammarAccess.getTalkAccess().getCommaKeyword_10_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getTalkRule());
						}
					}
					otherlv_11=RULE_STRING
					{
						newLeafNode(otherlv_11, grammarAccess.getTalkAccess().getPresentersPersonCrossReference_10_1_0());
					}
				)
			)
		)*
		otherlv_12=')'
		{
			newLeafNode(otherlv_12, grammarAccess.getTalkAccess().getRightParenthesisKeyword_11());
		}
		otherlv_13='}'
		{
			newLeafNode(otherlv_13, grammarAccess.getTalkAccess().getRightCurlyBracketKeyword_12());
		}
	)
;

// Entry rule entryRuleEquipment
entryRuleEquipment returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEquipmentRule()); }
	iv_ruleEquipment=ruleEquipment
	{ $current=$iv_ruleEquipment.current; }
	EOF;

// Rule Equipment
ruleEquipment returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			lv_equipmentName_0_0=RULE_STRING
			{
				newLeafNode(lv_equipmentName_0_0, grammarAccess.getEquipmentAccess().getEquipmentNameSTRINGTerminalRuleCall_0());
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getEquipmentRule());
				}
				setWithLastConsumed(
					$current,
					"equipmentName",
					lv_equipmentName_0_0,
					"org.eclipse.xtext.common.Terminals.STRING");
			}
		)
	)
;

// Rule Role
ruleRole returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='Presenter'
			{
				$current = grammarAccess.getRoleAccess().getPresenterEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getRoleAccess().getPresenterEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='TechSupport'
			{
				$current = grammarAccess.getRoleAccess().getTechSupportEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getRoleAccess().getTechSupportEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='Animator'
			{
				$current = grammarAccess.getRoleAccess().getAnimatorEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getRoleAccess().getAnimatorEnumLiteralDeclaration_2());
			}
		)
	)
;

// Rule LocationType
ruleLocationType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='Room'
			{
				$current = grammarAccess.getLocationTypeAccess().getRoomEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getLocationTypeAccess().getRoomEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='BreakArea'
			{
				$current = grammarAccess.getLocationTypeAccess().getBreakAreaEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getLocationTypeAccess().getBreakAreaEnumLiteralDeclaration_1());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
