/*
 * generated by Xtext 2.42.0
 */
grammar InternalAgendomat;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package agendomat.dsl.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package agendomat.dsl.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import agendomat.dsl.services.AgendomatGrammarAccess;

}

@parser::members {

 	private AgendomatGrammarAccess grammarAccess;

    public InternalAgendomatParser(TokenStream input, AgendomatGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Model";
   	}

   	@Override
   	protected AgendomatGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleModel
entryRuleModel returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getModelRule()); }
	iv_ruleModel=ruleModel
	{ $current=$iv_ruleModel.current; }
	EOF;

// Rule Model
ruleModel returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getModelAccess().getModelAction_0(),
					$current);
			}
		)
		otherlv_1='Model'
		{
			newLeafNode(otherlv_1, grammarAccess.getModelAccess().getModelKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='events'
			{
				newLeafNode(otherlv_3, grammarAccess.getModelAccess().getEventsKeyword_3_0());
			}
			otherlv_4='{'
			{
				newLeafNode(otherlv_4, grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_3_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getModelAccess().getEventsEventParserRuleCall_3_2_0());
					}
					lv_events_5_0=ruleEvent
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getModelRule());
						}
						add(
							$current,
							"events",
							lv_events_5_0,
							"agendomat.dsl.Agendomat.Event");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_6=','
				{
					newLeafNode(otherlv_6, grammarAccess.getModelAccess().getCommaKeyword_3_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getModelAccess().getEventsEventParserRuleCall_3_3_1_0());
						}
						lv_events_7_0=ruleEvent
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getModelRule());
							}
							add(
								$current,
								"events",
								lv_events_7_0,
								"agendomat.dsl.Agendomat.Event");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_8='}'
			{
				newLeafNode(otherlv_8, grammarAccess.getModelAccess().getRightCurlyBracketKeyword_3_4());
			}
		)?
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getModelAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleProgramItem
entryRuleProgramItem returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getProgramItemRule()); }
	iv_ruleProgramItem=ruleProgramItem
	{ $current=$iv_ruleProgramItem.current; }
	EOF;

// Rule ProgramItem
ruleProgramItem returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getProgramItemAccess().getSessionParserRuleCall_0());
		}
		this_Session_0=ruleSession
		{
			$current = $this_Session_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getProgramItemAccess().getBreakParserRuleCall_1());
		}
		this_Break_1=ruleBreak
		{
			$current = $this_Break_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleEvent
entryRuleEvent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEventRule()); }
	iv_ruleEvent=ruleEvent
	{ $current=$iv_ruleEvent.current; }
	EOF;

// Rule Event
ruleEvent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Event'
		{
			newLeafNode(otherlv_0, grammarAccess.getEventAccess().getEventKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='eventName'
		{
			newLeafNode(otherlv_2, grammarAccess.getEventAccess().getEventNameKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEventAccess().getEventNameEStringParserRuleCall_3_0());
				}
				lv_eventName_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventRule());
					}
					set(
						$current,
						"eventName",
						lv_eventName_3_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='eventStartDate'
		{
			newLeafNode(otherlv_4, grammarAccess.getEventAccess().getEventStartDateKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEventAccess().getEventStartDateEStringParserRuleCall_5_0());
				}
				lv_eventStartDate_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventRule());
					}
					set(
						$current,
						"eventStartDate",
						lv_eventStartDate_5_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='eventEndDate'
		{
			newLeafNode(otherlv_6, grammarAccess.getEventAccess().getEventEndDateKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEventAccess().getEventEndDateEStringParserRuleCall_7_0());
				}
				lv_eventEndDate_7_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventRule());
					}
					set(
						$current,
						"eventEndDate",
						lv_eventEndDate_7_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_8='desc'
			{
				newLeafNode(otherlv_8, grammarAccess.getEventAccess().getDescKeyword_8_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getEventAccess().getDescEStringParserRuleCall_8_1_0());
					}
					lv_desc_9_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getEventRule());
						}
						set(
							$current,
							"desc",
							lv_desc_9_0,
							"agendomat.dsl.Agendomat.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_10='persons'
			{
				newLeafNode(otherlv_10, grammarAccess.getEventAccess().getPersonsKeyword_9_0());
			}
			otherlv_11='{'
			{
				newLeafNode(otherlv_11, grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_9_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_9_2_0());
					}
					lv_persons_12_0=rulePerson
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getEventRule());
						}
						add(
							$current,
							"persons",
							lv_persons_12_0,
							"agendomat.dsl.Agendomat.Person");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_13=','
				{
					newLeafNode(otherlv_13, grammarAccess.getEventAccess().getCommaKeyword_9_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getEventAccess().getPersonsPersonParserRuleCall_9_3_1_0());
						}
						lv_persons_14_0=rulePerson
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getEventRule());
							}
							add(
								$current,
								"persons",
								lv_persons_14_0,
								"agendomat.dsl.Agendomat.Person");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_15='}'
			{
				newLeafNode(otherlv_15, grammarAccess.getEventAccess().getRightCurlyBracketKeyword_9_4());
			}
		)?
		(
			otherlv_16='programItems'
			{
				newLeafNode(otherlv_16, grammarAccess.getEventAccess().getProgramItemsKeyword_10_0());
			}
			otherlv_17='{'
			{
				newLeafNode(otherlv_17, grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_10_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_10_2_0());
					}
					lv_programItems_18_0=ruleProgramItem
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getEventRule());
						}
						add(
							$current,
							"programItems",
							lv_programItems_18_0,
							"agendomat.dsl.Agendomat.ProgramItem");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_19=','
				{
					newLeafNode(otherlv_19, grammarAccess.getEventAccess().getCommaKeyword_10_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getEventAccess().getProgramItemsProgramItemParserRuleCall_10_3_1_0());
						}
						lv_programItems_20_0=ruleProgramItem
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getEventRule());
							}
							add(
								$current,
								"programItems",
								lv_programItems_20_0,
								"agendomat.dsl.Agendomat.ProgramItem");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_21='}'
			{
				newLeafNode(otherlv_21, grammarAccess.getEventAccess().getRightCurlyBracketKeyword_10_4());
			}
		)?
		(
			otherlv_22='locations'
			{
				newLeafNode(otherlv_22, grammarAccess.getEventAccess().getLocationsKeyword_11_0());
			}
			otherlv_23='{'
			{
				newLeafNode(otherlv_23, grammarAccess.getEventAccess().getLeftCurlyBracketKeyword_11_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_11_2_0());
					}
					lv_locations_24_0=ruleLocation
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getEventRule());
						}
						add(
							$current,
							"locations",
							lv_locations_24_0,
							"agendomat.dsl.Agendomat.Location");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_25=','
				{
					newLeafNode(otherlv_25, grammarAccess.getEventAccess().getCommaKeyword_11_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getEventAccess().getLocationsLocationParserRuleCall_11_3_1_0());
						}
						lv_locations_26_0=ruleLocation
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getEventRule());
							}
							add(
								$current,
								"locations",
								lv_locations_26_0,
								"agendomat.dsl.Agendomat.Location");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_27='}'
			{
				newLeafNode(otherlv_27, grammarAccess.getEventAccess().getRightCurlyBracketKeyword_11_4());
			}
		)?
		otherlv_28='}'
		{
			newLeafNode(otherlv_28, grammarAccess.getEventAccess().getRightCurlyBracketKeyword_12());
		}
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRulePerson
entryRulePerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonRule()); }
	iv_rulePerson=rulePerson
	{ $current=$iv_rulePerson.current; }
	EOF;

// Rule Person
rulePerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Person'
		{
			newLeafNode(otherlv_0, grammarAccess.getPersonAccess().getPersonKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getPersonAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='personName'
		{
			newLeafNode(otherlv_2, grammarAccess.getPersonAccess().getPersonNameKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPersonAccess().getPersonNameEStringParserRuleCall_3_0());
				}
				lv_personName_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPersonRule());
					}
					set(
						$current,
						"personName",
						lv_personName_3_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='roles'
		{
			newLeafNode(otherlv_4, grammarAccess.getPersonAccess().getRolesKeyword_4());
		}
		otherlv_5='{'
		{
			newLeafNode(otherlv_5, grammarAccess.getPersonAccess().getLeftCurlyBracketKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_6_0());
				}
				lv_roles_6_0=ruleRole
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPersonRule());
					}
					add(
						$current,
						"roles",
						lv_roles_6_0,
						"agendomat.dsl.Agendomat.Role");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_7=','
			{
				newLeafNode(otherlv_7, grammarAccess.getPersonAccess().getCommaKeyword_7_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPersonAccess().getRolesRoleEnumRuleCall_7_1_0());
					}
					lv_roles_8_0=ruleRole
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPersonRule());
						}
						add(
							$current,
							"roles",
							lv_roles_8_0,
							"agendomat.dsl.Agendomat.Role");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getPersonAccess().getRightCurlyBracketKeyword_8());
		}
		otherlv_10='}'
		{
			newLeafNode(otherlv_10, grammarAccess.getPersonAccess().getRightCurlyBracketKeyword_9());
		}
	)
;

// Entry rule entryRuleLocation
entryRuleLocation returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLocationRule()); }
	iv_ruleLocation=ruleLocation
	{ $current=$iv_ruleLocation.current; }
	EOF;

// Rule Location
ruleLocation returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Location'
		{
			newLeafNode(otherlv_0, grammarAccess.getLocationAccess().getLocationKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getLocationAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='locationName'
		{
			newLeafNode(otherlv_2, grammarAccess.getLocationAccess().getLocationNameKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLocationAccess().getLocationNameEStringParserRuleCall_3_0());
				}
				lv_locationName_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLocationRule());
					}
					set(
						$current,
						"locationName",
						lv_locationName_3_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='locationType'
		{
			newLeafNode(otherlv_4, grammarAccess.getLocationAccess().getLocationTypeKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLocationAccess().getLocationTypeLocationTypeEnumRuleCall_5_0());
				}
				lv_locationType_5_0=ruleLocationType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLocationRule());
					}
					set(
						$current,
						"locationType",
						lv_locationType_5_0,
						"agendomat.dsl.Agendomat.LocationType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getLocationAccess().getRightCurlyBracketKeyword_6());
		}
	)
;

// Entry rule entryRuleSession
entryRuleSession returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSessionRule()); }
	iv_ruleSession=ruleSession
	{ $current=$iv_ruleSession.current; }
	EOF;

// Rule Session
ruleSession returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Session'
		{
			newLeafNode(otherlv_0, grammarAccess.getSessionAccess().getSessionKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='sessionName'
		{
			newLeafNode(otherlv_2, grammarAccess.getSessionAccess().getSessionNameKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSessionAccess().getSessionNameEStringParserRuleCall_3_0());
				}
				lv_sessionName_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSessionRule());
					}
					set(
						$current,
						"sessionName",
						lv_sessionName_3_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='startTime'
		{
			newLeafNode(otherlv_4, grammarAccess.getSessionAccess().getStartTimeKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSessionAccess().getStartTimeEStringParserRuleCall_5_0());
				}
				lv_startTime_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSessionRule());
					}
					set(
						$current,
						"startTime",
						lv_startTime_5_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='endTime'
		{
			newLeafNode(otherlv_6, grammarAccess.getSessionAccess().getEndTimeKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSessionAccess().getEndTimeEStringParserRuleCall_7_0());
				}
				lv_endTime_7_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSessionRule());
					}
					set(
						$current,
						"endTime",
						lv_endTime_7_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_8='location'
		{
			newLeafNode(otherlv_8, grammarAccess.getSessionAccess().getLocationKeyword_8());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSessionRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getSessionAccess().getLocationLocationCrossReference_9_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_10='techSupport'
			{
				newLeafNode(otherlv_10, grammarAccess.getSessionAccess().getTechSupportKeyword_10_0());
			}
			otherlv_11='('
			{
				newLeafNode(otherlv_11, grammarAccess.getSessionAccess().getLeftParenthesisKeyword_10_1());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getSessionRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_10_2_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_13=','
				{
					newLeafNode(otherlv_13, grammarAccess.getSessionAccess().getCommaKeyword_10_3_0());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getSessionRule());
							}
						}
						{
							newCompositeNode(grammarAccess.getSessionAccess().getTechSupportPersonCrossReference_10_3_1_0());
						}
						ruleEString
						{
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_15=')'
			{
				newLeafNode(otherlv_15, grammarAccess.getSessionAccess().getRightParenthesisKeyword_10_4());
			}
		)?
		(
			otherlv_16='talks'
			{
				newLeafNode(otherlv_16, grammarAccess.getSessionAccess().getTalksKeyword_11_0());
			}
			otherlv_17='{'
			{
				newLeafNode(otherlv_17, grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_11_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_2_0());
					}
					lv_talks_18_0=ruleTalk
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSessionRule());
						}
						add(
							$current,
							"talks",
							lv_talks_18_0,
							"agendomat.dsl.Agendomat.Talk");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_19=','
				{
					newLeafNode(otherlv_19, grammarAccess.getSessionAccess().getCommaKeyword_11_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getSessionAccess().getTalksTalkParserRuleCall_11_3_1_0());
						}
						lv_talks_20_0=ruleTalk
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getSessionRule());
							}
							add(
								$current,
								"talks",
								lv_talks_20_0,
								"agendomat.dsl.Agendomat.Talk");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_21='}'
			{
				newLeafNode(otherlv_21, grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_11_4());
			}
		)?
		(
			otherlv_22='equipment'
			{
				newLeafNode(otherlv_22, grammarAccess.getSessionAccess().getEquipmentKeyword_12_0());
			}
			otherlv_23='{'
			{
				newLeafNode(otherlv_23, grammarAccess.getSessionAccess().getLeftCurlyBracketKeyword_12_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_12_2_0());
					}
					lv_equipment_24_0=ruleEquipment
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSessionRule());
						}
						add(
							$current,
							"equipment",
							lv_equipment_24_0,
							"agendomat.dsl.Agendomat.Equipment");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_25=','
				{
					newLeafNode(otherlv_25, grammarAccess.getSessionAccess().getCommaKeyword_12_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getSessionAccess().getEquipmentEquipmentParserRuleCall_12_3_1_0());
						}
						lv_equipment_26_0=ruleEquipment
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getSessionRule());
							}
							add(
								$current,
								"equipment",
								lv_equipment_26_0,
								"agendomat.dsl.Agendomat.Equipment");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_27='}'
			{
				newLeafNode(otherlv_27, grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_12_4());
			}
		)?
		otherlv_28='}'
		{
			newLeafNode(otherlv_28, grammarAccess.getSessionAccess().getRightCurlyBracketKeyword_13());
		}
	)
;

// Entry rule entryRuleBreak
entryRuleBreak returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBreakRule()); }
	iv_ruleBreak=ruleBreak
	{ $current=$iv_ruleBreak.current; }
	EOF;

// Rule Break
ruleBreak returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Break'
		{
			newLeafNode(otherlv_0, grammarAccess.getBreakAccess().getBreakKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getBreakAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='breakName'
		{
			newLeafNode(otherlv_2, grammarAccess.getBreakAccess().getBreakNameKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getBreakAccess().getBreakNameEStringParserRuleCall_3_0());
				}
				lv_breakName_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBreakRule());
					}
					set(
						$current,
						"breakName",
						lv_breakName_3_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='startTime'
		{
			newLeafNode(otherlv_4, grammarAccess.getBreakAccess().getStartTimeKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getBreakAccess().getStartTimeEStringParserRuleCall_5_0());
				}
				lv_startTime_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBreakRule());
					}
					set(
						$current,
						"startTime",
						lv_startTime_5_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='endTime'
		{
			newLeafNode(otherlv_6, grammarAccess.getBreakAccess().getEndTimeKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getBreakAccess().getEndTimeEStringParserRuleCall_7_0());
				}
				lv_endTime_7_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBreakRule());
					}
					set(
						$current,
						"endTime",
						lv_endTime_7_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_8='location'
		{
			newLeafNode(otherlv_8, grammarAccess.getBreakAccess().getLocationKeyword_8());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBreakRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getBreakAccess().getLocationLocationCrossReference_9_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_10='animators'
			{
				newLeafNode(otherlv_10, grammarAccess.getBreakAccess().getAnimatorsKeyword_10_0());
			}
			otherlv_11='('
			{
				newLeafNode(otherlv_11, grammarAccess.getBreakAccess().getLeftParenthesisKeyword_10_1());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getBreakRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_10_2_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_13=','
				{
					newLeafNode(otherlv_13, grammarAccess.getBreakAccess().getCommaKeyword_10_3_0());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getBreakRule());
							}
						}
						{
							newCompositeNode(grammarAccess.getBreakAccess().getAnimatorsPersonCrossReference_10_3_1_0());
						}
						ruleEString
						{
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_15=')'
			{
				newLeafNode(otherlv_15, grammarAccess.getBreakAccess().getRightParenthesisKeyword_10_4());
			}
		)?
		otherlv_16='}'
		{
			newLeafNode(otherlv_16, grammarAccess.getBreakAccess().getRightCurlyBracketKeyword_11());
		}
	)
;

// Entry rule entryRuleTalk
entryRuleTalk returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTalkRule()); }
	iv_ruleTalk=ruleTalk
	{ $current=$iv_ruleTalk.current; }
	EOF;

// Rule Talk
ruleTalk returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Talk'
		{
			newLeafNode(otherlv_0, grammarAccess.getTalkAccess().getTalkKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getTalkAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='talkName'
		{
			newLeafNode(otherlv_2, grammarAccess.getTalkAccess().getTalkNameKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTalkAccess().getTalkNameEStringParserRuleCall_3_0());
				}
				lv_talkName_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTalkRule());
					}
					set(
						$current,
						"talkName",
						lv_talkName_3_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='talkStartTime'
		{
			newLeafNode(otherlv_4, grammarAccess.getTalkAccess().getTalkStartTimeKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTalkAccess().getTalkStartTimeEStringParserRuleCall_5_0());
				}
				lv_talkStartTime_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTalkRule());
					}
					set(
						$current,
						"talkStartTime",
						lv_talkStartTime_5_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='talkEndTime'
		{
			newLeafNode(otherlv_6, grammarAccess.getTalkAccess().getTalkEndTimeKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTalkAccess().getTalkEndTimeEStringParserRuleCall_7_0());
				}
				lv_talkEndTime_7_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTalkRule());
					}
					set(
						$current,
						"talkEndTime",
						lv_talkEndTime_7_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_8='presenters'
		{
			newLeafNode(otherlv_8, grammarAccess.getTalkAccess().getPresentersKeyword_8());
		}
		otherlv_9='('
		{
			newLeafNode(otherlv_9, grammarAccess.getTalkAccess().getLeftParenthesisKeyword_9());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTalkRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_10_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_11=','
			{
				newLeafNode(otherlv_11, grammarAccess.getTalkAccess().getCommaKeyword_11_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getTalkRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getTalkAccess().getPresentersPersonCrossReference_11_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_13=')'
		{
			newLeafNode(otherlv_13, grammarAccess.getTalkAccess().getRightParenthesisKeyword_12());
		}
		otherlv_14='}'
		{
			newLeafNode(otherlv_14, grammarAccess.getTalkAccess().getRightCurlyBracketKeyword_13());
		}
	)
;

// Entry rule entryRuleEquipment
entryRuleEquipment returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEquipmentRule()); }
	iv_ruleEquipment=ruleEquipment
	{ $current=$iv_ruleEquipment.current; }
	EOF;

// Rule Equipment
ruleEquipment returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Equipment'
		{
			newLeafNode(otherlv_0, grammarAccess.getEquipmentAccess().getEquipmentKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getEquipmentAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='equipmentName'
		{
			newLeafNode(otherlv_2, grammarAccess.getEquipmentAccess().getEquipmentNameKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEquipmentAccess().getEquipmentNameEStringParserRuleCall_3_0());
				}
				lv_equipmentName_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEquipmentRule());
					}
					set(
						$current,
						"equipmentName",
						lv_equipmentName_3_0,
						"agendomat.dsl.Agendomat.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_4='equipmentType'
			{
				newLeafNode(otherlv_4, grammarAccess.getEquipmentAccess().getEquipmentTypeKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getEquipmentAccess().getEquipmentTypeEStringParserRuleCall_4_1_0());
					}
					lv_equipmentType_5_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getEquipmentRule());
						}
						set(
							$current,
							"equipmentType",
							lv_equipmentType_5_0,
							"agendomat.dsl.Agendomat.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getEquipmentAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Rule Role
ruleRole returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='Presenter'
			{
				$current = grammarAccess.getRoleAccess().getPresenterEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getRoleAccess().getPresenterEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='TechSupport'
			{
				$current = grammarAccess.getRoleAccess().getTechSupportEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getRoleAccess().getTechSupportEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='Animator'
			{
				$current = grammarAccess.getRoleAccess().getAnimatorEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getRoleAccess().getAnimatorEnumLiteralDeclaration_2());
			}
		)
	)
;

// Rule LocationType
ruleLocationType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='Room'
			{
				$current = grammarAccess.getLocationTypeAccess().getRoomEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getLocationTypeAccess().getRoomEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='BreakArea'
			{
				$current = grammarAccess.getLocationTypeAccess().getBreakAreaEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getLocationTypeAccess().getBreakAreaEnumLiteralDeclaration_1());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
