/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AgendomatUiModule extends AbstractAgendomatUiModule {

	public AgendomatUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
