/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.serializer;

import agendomat.AgendomatPackage;
import agendomat.Break;
import agendomat.Equipment;
import agendomat.Event;
import agendomat.Location;
import agendomat.Person;
import agendomat.Session;
import agendomat.Talk;
import agendomat.dsl.services.AgendomatGrammarAccess;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class AgendomatSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private AgendomatGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == AgendomatPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case AgendomatPackage.BREAK:
				sequence_Break(context, (Break) semanticObject); 
				return; 
			case AgendomatPackage.EQUIPMENT:
				sequence_Equipment(context, (Equipment) semanticObject); 
				return; 
			case AgendomatPackage.EVENT:
				sequence_Event(context, (Event) semanticObject); 
				return; 
			case AgendomatPackage.LOCATION:
				sequence_Location(context, (Location) semanticObject); 
				return; 
			case AgendomatPackage.PERSON:
				sequence_Person(context, (Person) semanticObject); 
				return; 
			case AgendomatPackage.SESSION:
				sequence_Session(context, (Session) semanticObject); 
				return; 
			case AgendomatPackage.TALK:
				sequence_Talk(context, (Talk) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     ProgramItem returns Break
	 *     Break returns Break
	 *
	 * Constraint:
	 *     (breakName=STRING startTime=STRING endTime=STRING location=[Location|STRING] (animators+=[Person|STRING] animators+=[Person|STRING]*)?)
	 * </pre>
	 */
	protected void sequence_Break(ISerializationContext context, Break semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Equipment returns Equipment
	 *
	 * Constraint:
	 *     equipmentName=STRING
	 * </pre>
	 */
	protected void sequence_Equipment(ISerializationContext context, Equipment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AgendomatPackage.Literals.EQUIPMENT__EQUIPMENT_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AgendomatPackage.Literals.EQUIPMENT__EQUIPMENT_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEquipmentAccess().getEquipmentNameSTRINGTerminalRuleCall_0(), semanticObject.getEquipmentName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Event returns Event
	 *
	 * Constraint:
	 *     (
	 *         eventName=STRING 
	 *         ((eventStartDate=STRING eventEndDate=STRING) | eventStartDate=STRING) 
	 *         desc=STRING? 
	 *         persons+=Person* 
	 *         locations+=Location* 
	 *         programItems+=ProgramItem*
	 *     )
	 * </pre>
	 */
	protected void sequence_Event(ISerializationContext context, Event semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Location returns Location
	 *
	 * Constraint:
	 *     (locationName=STRING locationType=LocationType)
	 * </pre>
	 */
	protected void sequence_Location(ISerializationContext context, Location semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AgendomatPackage.Literals.LOCATION__LOCATION_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AgendomatPackage.Literals.LOCATION__LOCATION_NAME));
			if (transientValues.isValueTransient(semanticObject, AgendomatPackage.Literals.LOCATION__LOCATION_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AgendomatPackage.Literals.LOCATION__LOCATION_TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLocationAccess().getLocationNameSTRINGTerminalRuleCall_1_0(), semanticObject.getLocationName());
		feeder.accept(grammarAccess.getLocationAccess().getLocationTypeLocationTypeEnumRuleCall_3_0(), semanticObject.getLocationType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Person returns Person
	 *
	 * Constraint:
	 *     (personName=STRING roles+=Role roles+=Role*)
	 * </pre>
	 */
	protected void sequence_Person(ISerializationContext context, Person semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ProgramItem returns Session
	 *     Session returns Session
	 *
	 * Constraint:
	 *     (
	 *         sessionName=STRING 
	 *         startTime=STRING 
	 *         endTime=STRING 
	 *         location=[Location|STRING] 
	 *         (techSupport+=[Person|STRING] techSupport+=[Person|STRING]*)? 
	 *         (equipment+=Equipment equipment+=Equipment*)? 
	 *         talks+=Talk*
	 *     )
	 * </pre>
	 */
	protected void sequence_Session(ISerializationContext context, Session semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Talk returns Talk
	 *
	 * Constraint:
	 *     (talkName=STRING talkStartTime=STRING talkEndTime=STRING presenters+=[Person|STRING] presenters+=[Person|STRING]*)
	 * </pre>
	 */
	protected void sequence_Talk(ISerializationContext context, Talk semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
