/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.parser.antlr;

import agendomat.dsl.parser.antlr.internal.InternalAgendomatParser;
import agendomat.dsl.services.AgendomatGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AgendomatParser extends AbstractAntlrParser {

	@Inject
	private AgendomatGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAgendomatParser createParser(XtextTokenStream stream) {
		return new InternalAgendomatParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AgendomatGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AgendomatGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
