/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AgendomatAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("agendomat/dsl/parser/antlr/internal/InternalAgendomat.tokens");
	}
}
