/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.ui.tests;

import agendomat.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AgendomatUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("agendomat.dsl.Agendomat");
	}

}
