/**
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.formatting2;

import agendomat.Event;
import agendomat.Location;
import agendomat.Person;
import agendomat.ProgramItem;
import agendomat.dsl.services.AgendomatGrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class AgendomatFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private AgendomatGrammarAccess _agendomatGrammarAccess;

  protected void _format(final /* Model */Object model, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nevents cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final Event event, @Extension final IFormattableDocument document) {
    EList<Person> _persons = event.getPersons();
    for (final Person person : _persons) {
      document.<Person>format(person);
    }
    EList<ProgramItem> _programItems = event.getProgramItems();
    for (final ProgramItem programItem : _programItems) {
      document.<ProgramItem>format(programItem);
    }
    EList<Location> _locations = event.getLocations();
    for (final Location location : _locations) {
      document.<Location>format(location);
    }
  }

  @XbaseGenerated
  public void format(final Object event, final IFormattableDocument document) {
    if (event instanceof XtextResource) {
      _format((XtextResource)event, document);
      return;
    } else if (event instanceof Event) {
      _format((Event)event, document);
      return;
    } else if (event instanceof EObject) {
      _format((EObject)event, document);
      return;
    } else if (event == null) {
      _format((Void)null, document);
      return;
    } else if (event != null) {
      _format(event, document);
      return;
    } else if (event != null) {
      _format(event, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(event, document).toString());
    }
  }
}
