/*
 * generated by Xtext 2.42.0
 */
package agendomat.dsl.formatting2

import agendomat.Event
import agendomat.Model
import agendomat.dsl.services.AgendomatGrammarAccess
import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class AgendomatFormatter extends AbstractFormatter2 {
	
	@Inject extension AgendomatGrammarAccess

	def dispatch void format(Model model, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (event : model.events) {
			event.format
		}
	}

	def dispatch void format(Event event, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (person : event.persons) {
			person.format
		}
		for (programItem : event.programItems) {
			programItem.format
		}
		for (location : event.locations) {
			location.format
		}
	}
	
	// TODO: implement for Session
}
